namespace StardustSandbox.Enums.Indexers
{
    public enum ElementIndex : sbyte
    {
        None = -1,

        Dirt,
        Mud,
        Water,
        Stone,
        Grass,
        Ice,
        Sand,
        Snow,
        MCorruption,
        Lava,
        Acid,
        Glass,
        Iron,
        Wall,
        Wood,
        GCorruption,
        LCorruption,
        IMCorruption,
        Steam,
        Smoke,
        RedBrick,
        TreeLeaf,
        MountingBlock,
        Fire,
        Lamp,
        Void,
        Clone,
        Oil,
        Salt,
        Saltwater,
        Bomb,
        Dynamite,
        Tnt,
        DrySponge,
        WetSponge,
        Gold,
        Heater,
        Freezer,
        Ash,
    }
}
