//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.Localization.Localization.Messages", typeof(Localization_Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This will erase everything in the world, including elements and items, and reset it to empty. This cannot be undone. Continue?.
        /// </summary>
        internal static string Confirm_Simulation_EraseEverything_Description {
            get {
                return ResourceManager.GetString("Confirm.Simulation.EraseEverything.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erase all world content?.
        /// </summary>
        internal static string Confirm_Simulation_EraseEverything_Title {
            get {
                return ResourceManager.GetString("Confirm.Simulation.EraseEverything.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a If you exit now, unsaved progress will be lost. Save your work before leaving. Continue?.
        /// </summary>
        internal static string Confirm_Simulation_Exit_Description {
            get {
                return ResourceManager.GetString("Confirm.Simulation.Exit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exit the simulation?.
        /// </summary>
        internal static string Confirm_Simulation_Exit_Title {
            get {
                return ResourceManager.GetString("Confirm.Simulation.Exit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This will reload the simulation and reset the world to the file&apos;s initial state. If no file is loaded, the world will be cleared. This cannot be undone. Continue?.
        /// </summary>
        internal static string Confirm_Simulation_Reload_Description {
            get {
                return ResourceManager.GetString("Confirm.Simulation.Reload.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restart the world?.
        /// </summary>
        internal static string Confirm_Simulation_Reload_Title {
            get {
                return ResourceManager.GetString("Confirm.Simulation.Reload.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Changing the world size will delete all current content. Save your progress before continuing. Proceed with size change?.
        /// </summary>
        internal static string Confirm_World_Resize_Description {
            get {
                return ResourceManager.GetString("Confirm.World.Resize.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change world size? Progress will be lost.
        /// </summary>
        internal static string Confirm_World_Resize_Title {
            get {
                return ResourceManager.GetString("Confirm.World.Resize.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No temperature is being applied..
        /// </summary>
        internal static string Information_NoTemperature {
            get {
                return ResourceManager.GetString("Information.NoTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter a description for the world..
        /// </summary>
        internal static string Input_World_Description {
            get {
                return ResourceManager.GetString("Input.World.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The world description can&apos;t be empty. Please add one..
        /// </summary>
        internal static string Input_World_Description_Validation_Empty {
            get {
                return ResourceManager.GetString("Input.World.Description.Validation.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter a name for the world..
        /// </summary>
        internal static string Input_World_Name {
            get {
                return ResourceManager.GetString("Input.World.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The world name can&apos;t be empty. Please enter at least one character..
        /// </summary>
        internal static string Input_World_Name_Validation_Empty {
            get {
                return ResourceManager.GetString("Input.World.Name.Validation.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No description..
        /// </summary>
        internal static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Some settings, like language, only apply after restarting the game..
        /// </summary>
        internal static string Settings_RestartRequired {
            get {
                return ResourceManager.GetString("Settings.RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hey! Your world is much bigger now! Use {0}, {1}, {2} and {3} to move your camera!.
        /// </summary>
        internal static string Tutorial_Move {
            get {
                return ResourceManager.GetString("Tutorial.Move", resourceCulture);
            }
        }
    }
}
