//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_GUIs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_GUIs() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.Localization.Localization.GUIs", typeof(Localization_GUIs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close the current menu..
        /// </summary>
        internal static string Button_Exit_Description {
            get {
                return ResourceManager.GetString("Button.Exit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a And that&apos;s the end....
        /// </summary>
        internal static string Credits_Message_Finalization {
            get {
                return ResourceManager.GetString("Credits.Message.Finalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Thanks for Playing!.
        /// </summary>
        internal static string Credits_Message_ThankPlayer {
            get {
                return ResourceManager.GetString("Credits.Message.ThankPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To my parents..
        /// </summary>
        internal static string Credits_People_Parents {
            get {
                return ResourceManager.GetString("Credits.People.Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Artists.
        /// </summary>
        internal static string Credits_Title_Artists {
            get {
                return ResourceManager.GetString("Credits.Title.Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Composers.
        /// </summary>
        internal static string Credits_Title_Composers {
            get {
                return ResourceManager.GetString("Credits.Title.Composers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contributors.
        /// </summary>
        internal static string Credits_Title_Contributors {
            get {
                return ResourceManager.GetString("Credits.Title.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Creator.
        /// </summary>
        internal static string Credits_Title_Creator {
            get {
                return ResourceManager.GetString("Credits.Title.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Programming.
        /// </summary>
        internal static string Credits_Title_Programming {
            get {
                return ResourceManager.GetString("Credits.Title.Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Roles.
        /// </summary>
        internal static string Credits_Title_Roles {
            get {
                return ResourceManager.GetString("Credits.Title.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Special Thanks.
        /// </summary>
        internal static string Credits_Title_SpecialThanks {
            get {
                return ResourceManager.GetString("Credits.Title.SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Testers.
        /// </summary>
        internal static string Credits_Title_Testers {
            get {
                return ResourceManager.GetString("Credits.Title.Testers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tools.
        /// </summary>
        internal static string Credits_Title_Tools {
            get {
                return ResourceManager.GetString("Credits.Title.Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Generate content procedurally for your world to help with ideas!.
        /// </summary>
        internal static string EnvironmentSettings_Generator_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.Generator.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Generator.
        /// </summary>
        internal static string EnvironmentSettings_Generator_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.Generator.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change the world&apos;s temperatures..
        /// </summary>
        internal static string EnvironmentSettings_TemperatureEditor_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TemperatureEditor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Temperatures.
        /// </summary>
        internal static string EnvironmentSettings_TemperatureEditor_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TemperatureEditor.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the time to 03:00 PM..
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Afternoon_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Afternoon.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Afternoon.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Afternoon_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Afternoon.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the time to 06:00 AM..
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Dawn_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Dawn.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dawn.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Dawn_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Dawn.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the time to 12:00 PM..
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_EarlyAfternoon_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.EarlyAfternoon.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Early Afternoon.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_EarlyAfternoon_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.EarlyAfternoon.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the time to 03:00 AM..
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_EarlyMorning_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.EarlyMorning.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Early Morning.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_EarlyMorning_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.EarlyMorning.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the time to 06:00 PM..
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Evening_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Evening.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Evening.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Evening_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Evening.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the time to 00:00 AM..
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_LateNight_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.LateNight.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Late Night.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_LateNight_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.LateNight.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the time to 08:00 AM..
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Morning_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Morning.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Morning.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Morning_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Morning.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the time to 08:00 PM..
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Night_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Night.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Night_Name {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Night.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Time.
        /// </summary>
        internal static string EnvironmentSettings_TimeOfDay_Title {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeOfDay.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disable the time progression, freezing the current time..
        /// </summary>
        internal static string EnvironmentSettings_TimeState_Disable_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeState.Disable.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable the time progression, resuming the natural time flow..
        /// </summary>
        internal static string EnvironmentSettings_TimeState_Enable_Description {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeState.Enable.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a State.
        /// </summary>
        internal static string EnvironmentSettings_TimeState_Title {
            get {
                return ResourceManager.GetString("EnvironmentSettings.TimeState.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Environment Settings.
        /// </summary>
        internal static string EnvironmentSettings_Title {
            get {
                return ResourceManager.GetString("EnvironmentSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clouds will be located in the highest layers of the world..
        /// </summary>
        internal static string GeneratorSettings_Contents_Clouds_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Contents.Clouds.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clouds.
        /// </summary>
        internal static string GeneratorSettings_Contents_Clouds_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Contents.Clouds.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Two oceans are added at the horizontal extremities of the world..
        /// </summary>
        internal static string GeneratorSettings_Contents_Oceans_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Contents.Oceans.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oceans.
        /// </summary>
        internal static string GeneratorSettings_Contents_Oceans_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Contents.Oceans.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contents.
        /// </summary>
        internal static string GeneratorSettings_Contents_Title {
            get {
                return ResourceManager.GetString("GeneratorSettings.Contents.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The world will be perpetuated by natural life. Depending on the chosen theme, the type of vegetation can change considerably..
        /// </summary>
        internal static string GeneratorSettings_Contents_Vegetation_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Contents.Vegetation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vegetation.
        /// </summary>
        internal static string GeneratorSettings_Contents_Vegetation_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Contents.Vegetation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start the world generation process using the selected options..
        /// </summary>
        internal static string GeneratorSettings_Generate_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Generate.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Generate.
        /// </summary>
        internal static string GeneratorSettings_Generate_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Generate.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The generator will allocate content to the background layer..
        /// </summary>
        internal static string GeneratorSettings_Settings_Background_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Settings.Background.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background.
        /// </summary>
        internal static string GeneratorSettings_Settings_Background_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Settings.Background.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The generator will allocate content to the foreground layer..
        /// </summary>
        internal static string GeneratorSettings_Settings_Foreground_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Settings.Foreground.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foreground.
        /// </summary>
        internal static string GeneratorSettings_Settings_Foreground_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Settings.Foreground.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Settings.
        /// </summary>
        internal static string GeneratorSettings_Settings_Title {
            get {
                return ResourceManager.GetString("GeneratorSettings.Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dry and arid environment, dominated by sand, rocks, and minimal vegetation..
        /// </summary>
        internal static string GeneratorSettings_Theme_Desert_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Desert.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desert.
        /// </summary>
        internal static string GeneratorSettings_Theme_Desert_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Desert.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A vast and deep oceanic environment, with water, waves, and marine life..
        /// </summary>
        internal static string GeneratorSettings_Theme_Ocean_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Ocean.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocean.
        /// </summary>
        internal static string GeneratorSettings_Theme_Ocean_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Ocean.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A natural landscape, with vegetation, earth, stones and soft soil..
        /// </summary>
        internal static string GeneratorSettings_Theme_Plain_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Plain.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plain.
        /// </summary>
        internal static string GeneratorSettings_Theme_Plain_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Plain.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A cold and snowy environment, covered with ice and snow..
        /// </summary>
        internal static string GeneratorSettings_Theme_Snow_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Snow.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Snow.
        /// </summary>
        internal static string GeneratorSettings_Theme_Snow_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Snow.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Themes.
        /// </summary>
        internal static string GeneratorSettings_Theme_Title {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A fiery and volcanic environment, with lava flows and ash-covered terrain..
        /// </summary>
        internal static string GeneratorSettings_Theme_Volcanic_Description {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Volcanic.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Volcanic.
        /// </summary>
        internal static string GeneratorSettings_Theme_Volcanic_Name {
            get {
                return ResourceManager.GetString("GeneratorSettings.Theme.Volcanic.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Generator Settings.
        /// </summary>
        internal static string GeneratorSettings_Title {
            get {
                return ResourceManager.GetString("GeneratorSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change environment settings like weather and temperature..
        /// </summary>
        internal static string HUD_EnvironmentSettings_Description {
            get {
                return ResourceManager.GetString("HUD.EnvironmentSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Environment Settings.
        /// </summary>
        internal static string HUD_EnvironmentSettings_Name {
            get {
                return ResourceManager.GetString("HUD.EnvironmentSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Removes everything from the map and resets it to empty..
        /// </summary>
        internal static string HUD_EraseEverything_Description {
            get {
                return ResourceManager.GetString("HUD.EraseEverything.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erase Everything.
        /// </summary>
        internal static string HUD_EraseEverything_Name {
            get {
                return ResourceManager.GetString("HUD.EraseEverything.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Switch the pen to eraser mode to remove content..
        /// </summary>
        internal static string HUD_Eraser_Description {
            get {
                return ResourceManager.GetString("HUD.Eraser.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Eraser.
        /// </summary>
        internal static string HUD_Eraser_Name {
            get {
                return ResourceManager.GetString("HUD.Eraser.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open the main menu for settings and options..
        /// </summary>
        internal static string HUD_GameMenu_Description {
            get {
                return ResourceManager.GetString("HUD.GameMenu.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Game Menu.
        /// </summary>
        internal static string HUD_GameMenu_Name {
            get {
                return ResourceManager.GetString("HUD.GameMenu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a See information and stats about your world..
        /// </summary>
        internal static string HUD_Information_Description {
            get {
                return ResourceManager.GetString("HUD.Information.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Information.
        /// </summary>
        internal static string HUD_Information_Name {
            get {
                return ResourceManager.GetString("HUD.Information.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Browse and learn about all game elements, their features, and interactions..
        /// </summary>
        internal static string HUD_ItemExplorer_Description {
            get {
                return ResourceManager.GetString("HUD.ItemExplorer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item Explorer.
        /// </summary>
        internal static string HUD_ItemExplorer_Name {
            get {
                return ResourceManager.GetString("HUD.ItemExplorer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pause or resume the simulation..
        /// </summary>
        internal static string HUD_PauseSimulation_Description {
            get {
                return ResourceManager.GetString("HUD.PauseSimulation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pause/Resume Simulation.
        /// </summary>
        internal static string HUD_PauseSimulation_Name {
            get {
                return ResourceManager.GetString("HUD.PauseSimulation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change pen settings and how it works on the canvas..
        /// </summary>
        internal static string HUD_PenSettings_Description {
            get {
                return ResourceManager.GetString("HUD.PenSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pen Settings.
        /// </summary>
        internal static string HUD_PenSettings_Name {
            get {
                return ResourceManager.GetString("HUD.PenSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reload the last simulation or clear the map if none is loaded..
        /// </summary>
        internal static string HUD_ReloadSimulation_Description {
            get {
                return ResourceManager.GetString("HUD.ReloadSimulation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reload Simulation.
        /// </summary>
        internal static string HUD_ReloadSimulation_Name {
            get {
                return ResourceManager.GetString("HUD.ReloadSimulation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open the menu to save or manage worlds and simulations..
        /// </summary>
        internal static string HUD_SaveMenu_Description {
            get {
                return ResourceManager.GetString("HUD.SaveMenu.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Menu.
        /// </summary>
        internal static string HUD_SaveMenu_Name {
            get {
                return ResourceManager.GetString("HUD.SaveMenu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simulation Paused.
        /// </summary>
        internal static string HUD_SimulationPaused {
            get {
                return ResourceManager.GetString("HUD.SimulationPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change simulation speed. Higher speeds may slow performance..
        /// </summary>
        internal static string HUD_Speed_Description {
            get {
                return ResourceManager.GetString("HUD.Speed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simulation Speed.
        /// </summary>
        internal static string HUD_Speed_Name {
            get {
                return ResourceManager.GetString("HUD.Speed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change world settings..
        /// </summary>
        internal static string HUD_WorldSettings_Description {
            get {
                return ResourceManager.GetString("HUD.WorldSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a World Settings.
        /// </summary>
        internal static string HUD_WorldSettings_Name {
            get {
                return ResourceManager.GetString("HUD.WorldSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background Elements.
        /// </summary>
        internal static string Information_Field_BackgroundElements {
            get {
                return ResourceManager.GetString("Information.Field.BackgroundElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foreground Elements.
        /// </summary>
        internal static string Information_Field_ForegroundElements {
            get {
                return ResourceManager.GetString("Information.Field.ForegroundElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Information.
        /// </summary>
        internal static string Information_Title {
            get {
                return ResourceManager.GetString("Information.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item Explorer.
        /// </summary>
        internal static string ItemExplorer_Title {
            get {
                return ResourceManager.GetString("ItemExplorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        internal static string Main_Create {
            get {
                return ResourceManager.GetString("Main.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credits.
        /// </summary>
        internal static string Main_Credits {
            get {
                return ResourceManager.GetString("Main.Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        internal static string Main_Options {
            get {
                return ResourceManager.GetString("Main.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Play.
        /// </summary>
        internal static string Main_Play {
            get {
                return ResourceManager.GetString("Main.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quit.
        /// </summary>
        internal static string Main_Quit {
            get {
                return ResourceManager.GetString("Main.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type a shortcut key to clear the world..
        /// </summary>
        internal static string Options_Controls_ClearWorld_Description {
            get {
                return ResourceManager.GetString("Options.Controls.ClearWorld.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clear World.
        /// </summary>
        internal static string Options_Controls_ClearWorld_Name {
            get {
                return ResourceManager.GetString("Options.Controls.ClearWorld.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configure the keys and buttons associated with the game controls..
        /// </summary>
        internal static string Options_Controls_Description {
            get {
                return ResourceManager.GetString("Options.Controls.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press a key on the keyboard to move down..
        /// </summary>
        internal static string Options_Controls_MoveCameraDown_Description {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraDown.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Down.
        /// </summary>
        internal static string Options_Controls_MoveCameraDown_Name {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraDown.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type a shortcut key to move the camera faster..
        /// </summary>
        internal static string Options_Controls_MoveCameraFast_Description {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraFast.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Move Fast.
        /// </summary>
        internal static string Options_Controls_MoveCameraFast_Name {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraFast.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press a key on the keyboard to move left..
        /// </summary>
        internal static string Options_Controls_MoveCameraLeft_Description {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraLeft.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Left.
        /// </summary>
        internal static string Options_Controls_MoveCameraLeft_Name {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraLeft.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press a key on the keyboard to move to the right..
        /// </summary>
        internal static string Options_Controls_MoveCameraRight_Description {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraRight.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Right.
        /// </summary>
        internal static string Options_Controls_MoveCameraRight_Name {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraRight.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press a key on the keyboard to move upwards..
        /// </summary>
        internal static string Options_Controls_MoveCameraUp_Description {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraUp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Up.
        /// </summary>
        internal static string Options_Controls_MoveCameraUp_Name {
            get {
                return ResourceManager.GetString("Options.Controls.MoveCameraUp.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Controls.
        /// </summary>
        internal static string Options_Controls_Name {
            get {
                return ResourceManager.GetString("Options.Controls.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type a shortcut key to select the next shape..
        /// </summary>
        internal static string Options_Controls_NextShape_Description {
            get {
                return ResourceManager.GetString("Options.Controls.NextShape.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next Shape.
        /// </summary>
        internal static string Options_Controls_NextShape_Name {
            get {
                return ResourceManager.GetString("Options.Controls.NextShape.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type a shortcut key to capture the screen content and save it to a local image file..
        /// </summary>
        internal static string Options_Controls_Screenshot_Description {
            get {
                return ResourceManager.GetString("Options.Controls.Screenshot.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Screenshot.
        /// </summary>
        internal static string Options_Controls_Screenshot_Name {
            get {
                return ResourceManager.GetString("Options.Controls.Screenshot.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type a shortcut key to pause the world..
        /// </summary>
        internal static string Options_Controls_TogglePause_Description {
            get {
                return ResourceManager.GetString("Options.Controls.TogglePause.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pause.
        /// </summary>
        internal static string Options_Controls_TogglePause_Name {
            get {
                return ResourceManager.GetString("Options.Controls.TogglePause.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the background color of the cursor..
        /// </summary>
        internal static string Options_Cursor_BackgroundColor_Description {
            get {
                return ResourceManager.GetString("Options.Cursor.BackgroundColor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background Color.
        /// </summary>
        internal static string Options_Cursor_BackgroundColor_Name {
            get {
                return ResourceManager.GetString("Options.Cursor.BackgroundColor.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the color of the cursor..
        /// </summary>
        internal static string Options_Cursor_Color_Description {
            get {
                return ResourceManager.GetString("Options.Cursor.Color.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Color.
        /// </summary>
        internal static string Options_Cursor_Color_Name {
            get {
                return ResourceManager.GetString("Options.Cursor.Color.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Customize the appearance and behavior of the mouse cursor..
        /// </summary>
        internal static string Options_Cursor_Description {
            get {
                return ResourceManager.GetString("Options.Cursor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cursor.
        /// </summary>
        internal static string Options_Cursor_Name {
            get {
                return ResourceManager.GetString("Options.Cursor.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the transparency level of the cursor..
        /// </summary>
        internal static string Options_Cursor_Opacity_Description {
            get {
                return ResourceManager.GetString("Options.Cursor.Opacity.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opacity.
        /// </summary>
        internal static string Options_Cursor_Opacity_Name {
            get {
                return ResourceManager.GetString("Options.Cursor.Opacity.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjust the size of the cursor..
        /// </summary>
        internal static string Options_Cursor_Scale_Description {
            get {
                return ResourceManager.GetString("Options.Cursor.Scale.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scale.
        /// </summary>
        internal static string Options_Cursor_Scale_Name {
            get {
                return ResourceManager.GetString("Options.Cursor.Scale.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjust gameplay-related preferences..
        /// </summary>
        internal static string Options_Gameplay_Description {
            get {
                return ResourceManager.GetString("Options.Gameplay.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configure the opacity level of the world grid..
        /// </summary>
        internal static string Options_Gameplay_GridOpacity_Description {
            get {
                return ResourceManager.GetString("Options.Gameplay.GridOpacity.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grid Opacity.
        /// </summary>
        internal static string Options_Gameplay_GridOpacity_Name {
            get {
                return ResourceManager.GetString("Options.Gameplay.GridOpacity.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gameplay.
        /// </summary>
        internal static string Options_Gameplay_Name {
            get {
                return ResourceManager.GetString("Options.Gameplay.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose the color for the preview area displayed during gameplay..
        /// </summary>
        internal static string Options_Gameplay_PreviewAreaColor_Description {
            get {
                return ResourceManager.GetString("Options.Gameplay.PreviewAreaColor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preview Area Color.
        /// </summary>
        internal static string Options_Gameplay_PreviewAreaColor_Name {
            get {
                return ResourceManager.GetString("Options.Gameplay.PreviewAreaColor.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the transparency level of the preview area..
        /// </summary>
        internal static string Options_Gameplay_PreviewAreaOpacity_Description {
            get {
                return ResourceManager.GetString("Options.Gameplay.PreviewAreaOpacity.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preview Area Opacity.
        /// </summary>
        internal static string Options_Gameplay_PreviewAreaOpacity_Name {
            get {
                return ResourceManager.GetString("Options.Gameplay.PreviewAreaOpacity.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configure whether or not the world grid should be displayed..
        /// </summary>
        internal static string Options_Gameplay_ShowGrid_Description {
            get {
                return ResourceManager.GetString("Options.Gameplay.ShowGrid.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show Grid.
        /// </summary>
        internal static string Options_Gameplay_ShowGrid_Name {
            get {
                return ResourceManager.GetString("Options.Gameplay.ShowGrid.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configure whether or not the mouse preview area for element placement should be displayed..
        /// </summary>
        internal static string Options_Gameplay_ShowPreviewArea_Description {
            get {
                return ResourceManager.GetString("Options.Gameplay.ShowPreviewArea.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show Preview Area.
        /// </summary>
        internal static string Options_Gameplay_ShowPreviewArea_Name {
            get {
                return ResourceManager.GetString("Options.Gameplay.ShowPreviewArea.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Determine whether or not the elements should have color changes associated with their current temperatures..
        /// </summary>
        internal static string Options_Gameplay_ShowTemperatureColorVariations_Description {
            get {
                return ResourceManager.GetString("Options.Gameplay.ShowTemperatureColorVariations.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Temperature Color.
        /// </summary>
        internal static string Options_Gameplay_ShowTemperatureColorVariations_Name {
            get {
                return ResourceManager.GetString("Options.Gameplay.ShowTemperatureColorVariations.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Basic game settings, including language and accessibility..
        /// </summary>
        internal static string Options_General_Description {
            get {
                return ResourceManager.GetString("Options.General.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select the language for the game interface..
        /// </summary>
        internal static string Options_General_Language_Description {
            get {
                return ResourceManager.GetString("Options.General.Language.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string Options_General_Language_Name {
            get {
                return ResourceManager.GetString("Options.General.Language.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General.
        /// </summary>
        internal static string Options_General_Name {
            get {
                return ResourceManager.GetString("Options.General.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saves and applies all modified options..
        /// </summary>
        internal static string Options_Save_Description {
            get {
                return ResourceManager.GetString("Options.Save.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OPTIONS.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable borderless windowed mode..
        /// </summary>
        internal static string Options_Video_Borderless_Description {
            get {
                return ResourceManager.GetString("Options.Video.Borderless.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Borderless.
        /// </summary>
        internal static string Options_Video_Borderless_Name {
            get {
                return ResourceManager.GetString("Options.Video.Borderless.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modify video-related settings, including resolution and display modes..
        /// </summary>
        internal static string Options_Video_Description {
            get {
                return ResourceManager.GetString("Options.Video.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Frame Rate is how many images the game shows per second. Higher rates make motion smoother..
        /// </summary>
        internal static string Options_Video_Framerate_Description {
            get {
                return ResourceManager.GetString("Options.Video.Framerate.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Frame Rate.
        /// </summary>
        internal static string Options_Video_Framerate_Name {
            get {
                return ResourceManager.GetString("Options.Video.Framerate.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable or disable fullscreen mode..
        /// </summary>
        internal static string Options_Video_Fullscreen_Description {
            get {
                return ResourceManager.GetString("Options.Video.Fullscreen.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fullscreen.
        /// </summary>
        internal static string Options_Video_Fullscreen_Name {
            get {
                return ResourceManager.GetString("Options.Video.Fullscreen.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video.
        /// </summary>
        internal static string Options_Video_Name {
            get {
                return ResourceManager.GetString("Options.Video.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select the screen resolution for the game..
        /// </summary>
        internal static string Options_Video_Resolution_Description {
            get {
                return ResourceManager.GetString("Options.Video.Resolution.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolution.
        /// </summary>
        internal static string Options_Video_Resolution_Name {
            get {
                return ResourceManager.GetString("Options.Video.Resolution.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turn vertical synchronization on or off to avoid screen tearing..
        /// </summary>
        internal static string Options_Video_VSync_Description {
            get {
                return ResourceManager.GetString("Options.Video.VSync.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VSync.
        /// </summary>
        internal static string Options_Video_VSync_Name {
            get {
                return ResourceManager.GetString("Options.Video.VSync.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Control audio levels for different categories..
        /// </summary>
        internal static string Options_Volume_Description {
            get {
                return ResourceManager.GetString("Options.Volume.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjust the overall game volume..
        /// </summary>
        internal static string Options_Volume_MasterVolume_Description {
            get {
                return ResourceManager.GetString("Options.Volume.MasterVolume.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Master Volume.
        /// </summary>
        internal static string Options_Volume_MasterVolume_Name {
            get {
                return ResourceManager.GetString("Options.Volume.MasterVolume.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the volume for background music..
        /// </summary>
        internal static string Options_Volume_MusicVolume_Description {
            get {
                return ResourceManager.GetString("Options.Volume.MusicVolume.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Music Volume.
        /// </summary>
        internal static string Options_Volume_MusicVolume_Name {
            get {
                return ResourceManager.GetString("Options.Volume.MusicVolume.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Volume.
        /// </summary>
        internal static string Options_Volume_Name {
            get {
                return ResourceManager.GetString("Options.Volume.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjust the sound effects volume..
        /// </summary>
        internal static string Options_Volume_SFXVolume_Description {
            get {
                return ResourceManager.GetString("Options.Volume.SFXVolume.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SFX Volume.
        /// </summary>
        internal static string Options_Volume_SFXVolume_Name {
            get {
                return ResourceManager.GetString("Options.Volume.SFXVolume.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pause.
        /// </summary>
        internal static string Pause_Title {
            get {
                return ResourceManager.GetString("Pause.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brush size is set to {0}..
        /// </summary>
        internal static string PenSettings_BrushSize_Slider_Description {
            get {
                return ResourceManager.GetString("PenSettings.BrushSize.Slider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brush Size.
        /// </summary>
        internal static string PenSettings_BrushSize_Slider_Name {
            get {
                return ResourceManager.GetString("PenSettings.BrushSize.Slider.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brush Size.
        /// </summary>
        internal static string PenSettings_BrushSize_Title {
            get {
                return ResourceManager.GetString("PenSettings.BrushSize.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Place items on the back layer..
        /// </summary>
        internal static string PenSettings_Layer_Back_Description {
            get {
                return ResourceManager.GetString("PenSettings.Layer.Back.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background Layer.
        /// </summary>
        internal static string PenSettings_Layer_Back_Name {
            get {
                return ResourceManager.GetString("PenSettings.Layer.Back.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Place items on the front layer..
        /// </summary>
        internal static string PenSettings_Layer_Front_Description {
            get {
                return ResourceManager.GetString("PenSettings.Layer.Front.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foreground.
        /// </summary>
        internal static string PenSettings_Layer_Front_Name {
            get {
                return ResourceManager.GetString("PenSettings.Layer.Front.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Layer.
        /// </summary>
        internal static string PenSettings_Layer_Title {
            get {
                return ResourceManager.GetString("PenSettings.Layer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose whether you want to hide or show the background layer..
        /// </summary>
        internal static string PenSettings_LayerVisibility_ShowOrHideBackgroundLayer_Description {
            get {
                return ResourceManager.GetString("PenSettings.LayerVisibility.ShowOrHideBackgroundLayer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background (Show/Hide).
        /// </summary>
        internal static string PenSettings_LayerVisibility_ShowOrHideBackgroundLayer_Name {
            get {
                return ResourceManager.GetString("PenSettings.LayerVisibility.ShowOrHideBackgroundLayer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose whether you want to hide or show the foreground layer..
        /// </summary>
        internal static string PenSettings_LayerVisibility_ShowOrHideForegroundLayer_Description {
            get {
                return ResourceManager.GetString("PenSettings.LayerVisibility.ShowOrHideForegroundLayer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foreground (Show/Hide).
        /// </summary>
        internal static string PenSettings_LayerVisibility_ShowOrHideForegroundLayer_Name {
            get {
                return ResourceManager.GetString("PenSettings.LayerVisibility.ShowOrHideForegroundLayer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set pen shape to circle..
        /// </summary>
        internal static string PenSettings_Shape_Circle_Description {
            get {
                return ResourceManager.GetString("PenSettings.Shape.Circle.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Circle Shape.
        /// </summary>
        internal static string PenSettings_Shape_Circle_Name {
            get {
                return ResourceManager.GetString("PenSettings.Shape.Circle.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set pen shape to square..
        /// </summary>
        internal static string PenSettings_Shape_Square_Description {
            get {
                return ResourceManager.GetString("PenSettings.Shape.Square.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Square Shape.
        /// </summary>
        internal static string PenSettings_Shape_Square_Name {
            get {
                return ResourceManager.GetString("PenSettings.Shape.Square.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shape.
        /// </summary>
        internal static string PenSettings_Shape_Title {
            get {
                return ResourceManager.GetString("PenSettings.Shape.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set pen shape to triangle..
        /// </summary>
        internal static string PenSettings_Shape_Triangle_Description {
            get {
                return ResourceManager.GetString("PenSettings.Shape.Triangle.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Triangle Shape.
        /// </summary>
        internal static string PenSettings_Shape_Triangle_Name {
            get {
                return ResourceManager.GetString("PenSettings.Shape.Triangle.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pen Settings.
        /// </summary>
        internal static string PenSettings_Title {
            get {
                return ResourceManager.GetString("PenSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tool.
        /// </summary>
        internal static string PenSettings_Tool_Title {
            get {
                return ResourceManager.GetString("PenSettings.Tool.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Play.
        /// </summary>
        internal static string Play_Title {
            get {
                return ResourceManager.GetString("Play.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string Save_Description_Title {
            get {
                return ResourceManager.GetString("Save.Description.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string Save_Name_Title {
            get {
                return ResourceManager.GetString("Save.Name.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save the world to a file. Overwrites if the name already exists..
        /// </summary>
        internal static string Save_Save_Description {
            get {
                return ResourceManager.GetString("Save.Save.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Thumbnail.
        /// </summary>
        internal static string Save_Thumbnail_Title {
            get {
                return ResourceManager.GetString("Save.Thumbnail.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Settings.
        /// </summary>
        internal static string Save_Title {
            get {
                return ResourceManager.GetString("Save.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Temperature Settings.
        /// </summary>
        internal static string TemperatureSettings_Name {
            get {
                return ResourceManager.GetString("TemperatureSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mildly cold temperature effect..
        /// </summary>
        internal static string TemperatureSettings_Temperature_Cold_Description {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.Cold.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cold.
        /// </summary>
        internal static string TemperatureSettings_Temperature_Cold_Name {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.Cold.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mildly hot temperature effect..
        /// </summary>
        internal static string TemperatureSettings_Temperature_Hot_Description {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.Hot.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hot.
        /// </summary>
        internal static string TemperatureSettings_Temperature_Hot_Name {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.Hot.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No temperature effect..
        /// </summary>
        internal static string TemperatureSettings_Temperature_None_Description {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.None.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a None.
        /// </summary>
        internal static string TemperatureSettings_Temperature_None_Name {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.None.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Normal temperature effect..
        /// </summary>
        internal static string TemperatureSettings_Temperature_Normal_Description {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.Normal.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Normal.
        /// </summary>
        internal static string TemperatureSettings_Temperature_Normal_Name {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.Normal.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extremely cold temperature effect..
        /// </summary>
        internal static string TemperatureSettings_Temperature_VeryCold_Description {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.VeryCold.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Very Cold.
        /// </summary>
        internal static string TemperatureSettings_Temperature_VeryCold_Name {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.VeryCold.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extremely hot temperature effect..
        /// </summary>
        internal static string TemperatureSettings_Temperature_VeryHot_Description {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.VeryHot.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Very Hot.
        /// </summary>
        internal static string TemperatureSettings_Temperature_VeryHot_Name {
            get {
                return ResourceManager.GetString("TemperatureSettings.Temperature.VeryHot.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Afternoon.
        /// </summary>
        internal static string TemperatureSettings_TimeOfDay_Afternoon {
            get {
                return ResourceManager.GetString("TemperatureSettings.TimeOfDay.Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dawn.
        /// </summary>
        internal static string TemperatureSettings_TimeOfDay_Dawn {
            get {
                return ResourceManager.GetString("TemperatureSettings.TimeOfDay.Dawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Early Afternoon.
        /// </summary>
        internal static string TemperatureSettings_TimeOfDay_EarlyAfternoon {
            get {
                return ResourceManager.GetString("TemperatureSettings.TimeOfDay.EarlyAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Early Morning.
        /// </summary>
        internal static string TemperatureSettings_TimeOfDay_EarlyMorning {
            get {
                return ResourceManager.GetString("TemperatureSettings.TimeOfDay.EarlyMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Evening.
        /// </summary>
        internal static string TemperatureSettings_TimeOfDay_Evening {
            get {
                return ResourceManager.GetString("TemperatureSettings.TimeOfDay.Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Late Night.
        /// </summary>
        internal static string TemperatureSettings_TimeOfDay_LateNight {
            get {
                return ResourceManager.GetString("TemperatureSettings.TimeOfDay.LateNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Morning.
        /// </summary>
        internal static string TemperatureSettings_TimeOfDay_Morning {
            get {
                return ResourceManager.GetString("TemperatureSettings.TimeOfDay.Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night.
        /// </summary>
        internal static string TemperatureSettings_TimeOfDay_Night {
            get {
                return ResourceManager.GetString("TemperatureSettings.TimeOfDay.Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Color Picker.
        /// </summary>
        internal static string Tools_ColorPicker_Title {
            get {
                return ResourceManager.GetString("Tools.ColorPicker.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current Page.
        /// </summary>
        internal static string WorldExplorer_CurrentPage {
            get {
                return ResourceManager.GetString("WorldExplorer.CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open Directory in Explorer.
        /// </summary>
        internal static string WorldExplorer_OpenInDirectory_Name {
            get {
                return ResourceManager.GetString("WorldExplorer.OpenInDirectory.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a World Explorer.
        /// </summary>
        internal static string WorldExplorer_Title {
            get {
                return ResourceManager.GetString("WorldExplorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 240x138 - Designed for expansive gameplay areas. May impact performance on lower-end systems..
        /// </summary>
        internal static string WorldSettings_Size_Large_Description {
            get {
                return ResourceManager.GetString("WorldSettings.Size.Large.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Large.
        /// </summary>
        internal static string WorldSettings_Size_Large_Name {
            get {
                return ResourceManager.GetString("WorldSettings.Size.Large.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 120x69 - Balanced for most gameplay scenarios..
        /// </summary>
        internal static string WorldSettings_Size_Medium_Description {
            get {
                return ResourceManager.GetString("WorldSettings.Size.Medium.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medium.
        /// </summary>
        internal static string WorldSettings_Size_Medium_Name {
            get {
                return ResourceManager.GetString("WorldSettings.Size.Medium.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 160x92 - Provides ample space for exploration..
        /// </summary>
        internal static string WorldSettings_Size_MediumLarge_Description {
            get {
                return ResourceManager.GetString("WorldSettings.Size.MediumLarge.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medium Large.
        /// </summary>
        internal static string WorldSettings_Size_MediumLarge_Name {
            get {
                return ResourceManager.GetString("WorldSettings.Size.MediumLarge.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 80x46 - Allows limited free movement..
        /// </summary>
        internal static string WorldSettings_Size_MediumSmall_Description {
            get {
                return ResourceManager.GetString("WorldSettings.Size.MediumSmall.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medium Small.
        /// </summary>
        internal static string WorldSettings_Size_MediumSmall_Name {
            get {
                return ResourceManager.GetString("WorldSettings.Size.MediumSmall.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 40x23 - Fits entirely within the player&apos;s camera..
        /// </summary>
        internal static string WorldSettings_Size_Small_Description {
            get {
                return ResourceManager.GetString("WorldSettings.Size.Small.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Small.
        /// </summary>
        internal static string WorldSettings_Size_Small_Name {
            get {
                return ResourceManager.GetString("WorldSettings.Size.Small.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sizes.
        /// </summary>
        internal static string WorldSettings_Size_Title {
            get {
                return ResourceManager.GetString("WorldSettings.Size.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 320x184 - Best for epic-scale worlds. May impact performance on lower-end systems..
        /// </summary>
        internal static string WorldSettings_Size_VeryLarge_Description {
            get {
                return ResourceManager.GetString("WorldSettings.Size.VeryLarge.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Very Large.
        /// </summary>
        internal static string WorldSettings_Size_VeryLarge_Name {
            get {
                return ResourceManager.GetString("WorldSettings.Size.VeryLarge.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a World Settings.
        /// </summary>
        internal static string WorldSettings_Title {
            get {
                return ResourceManager.GetString("WorldSettings.Title", resourceCulture);
            }
        }
    }
}
