//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Elements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Elements() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.Localization.Localization.Elements", typeof(Localization_Elements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intense heat that quickly burns flammable materials and spreads destruction..
        /// </summary>
        internal static string Energy_Fire_Description {
            get {
                return ResourceManager.GetString("Energy.Fire.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fire.
        /// </summary>
        internal static string Energy_Fire_Name {
            get {
                return ResourceManager.GetString("Energy.Fire.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Energy_Lightning_Description {
            get {
                return ResourceManager.GetString("Energy.Lightning.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Energy_Lightning_Name {
            get {
                return ResourceManager.GetString("Energy.Lightning.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A gaseous antidote that attempts, by all means, to contain the destruction caused by corruption and restore the environment to its original state..
        /// </summary>
        internal static string Gas_AntiCorruption_Description {
            get {
                return ResourceManager.GetString("Gas.AntiCorruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anti Corruption.
        /// </summary>
        internal static string Gas_AntiCorruption_Name {
            get {
                return ResourceManager.GetString("Gas.AntiCorruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dense, saturated cloud formed from the clustering of multiple clouds. When concentrated enough, it releases water or snow depending on temperature..
        /// </summary>
        internal static string Gas_ChargedCloud_Description {
            get {
                return ResourceManager.GetString("Gas.ChargedCloud.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Charged Cloud.
        /// </summary>
        internal static string Gas_ChargedCloud_Name {
            get {
                return ResourceManager.GetString("Gas.ChargedCloud.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cloud.
        /// </summary>
        internal static string Gas_Cloud_Description {
            get {
                return ResourceManager.GetString("Gas.Cloud.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cloud.
        /// </summary>
        internal static string Gas_Cloud_Name {
            get {
                return ResourceManager.GetString("Gas.Cloud.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gaseous corruption that spreads and contaminates the environment, making it inhospitable..
        /// </summary>
        internal static string Gas_Corruption_Description {
            get {
                return ResourceManager.GetString("Gas.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (gas).
        /// </summary>
        internal static string Gas_Corruption_Name {
            get {
                return ResourceManager.GetString("Gas.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Gas_LiquefiedPetroleumGas_Description {
            get {
                return ResourceManager.GetString("Gas.LiquefiedPetroleumGas.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Gas_LiquefiedPetroleumGas_Name {
            get {
                return ResourceManager.GetString("Gas.LiquefiedPetroleumGas.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Smoke from burning, rises slowly and darkens the air, showing fire is present..
        /// </summary>
        internal static string Gas_Smoke_Description {
            get {
                return ResourceManager.GetString("Gas.Smoke.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Smoke.
        /// </summary>
        internal static string Gas_Smoke_Name {
            get {
                return ResourceManager.GetString("Gas.Smoke.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hot water vapor that rises rapidly and disperses in the air. At high altitudes, it can turn into clouds..
        /// </summary>
        internal static string Gas_Steam_Description {
            get {
                return ResourceManager.GetString("Gas.Steam.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Steam.
        /// </summary>
        internal static string Gas_Steam_Name {
            get {
                return ResourceManager.GetString("Gas.Steam.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corrosive liquid that quickly dissolves many materials on contact..
        /// </summary>
        internal static string Liquid_Acid_Description {
            get {
                return ResourceManager.GetString("Liquid.Acid.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acid.
        /// </summary>
        internal static string Liquid_Acid_Name {
            get {
                return ResourceManager.GetString("Liquid.Acid.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contaminating liquid that flows and corrupts everything it touches..
        /// </summary>
        internal static string Liquid_Corruption_Description {
            get {
                return ResourceManager.GetString("Liquid.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (liquid).
        /// </summary>
        internal static string Liquid_Corruption_Name {
            get {
                return ResourceManager.GetString("Liquid.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Molten rock that burns almost everything it touches. It cools and hardens when exposed to cold..
        /// </summary>
        internal static string Liquid_Lava_Description {
            get {
                return ResourceManager.GetString("Liquid.Lava.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lava.
        /// </summary>
        internal static string Liquid_Lava_Name {
            get {
                return ResourceManager.GetString("Liquid.Lava.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dark, thick, very flammable liquid with low density..
        /// </summary>
        internal static string Liquid_Oil_Description {
            get {
                return ResourceManager.GetString("Liquid.Oil.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oil.
        /// </summary>
        internal static string Liquid_Oil_Name {
            get {
                return ResourceManager.GetString("Liquid.Oil.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Light blue liquid with floating salt particles..
        /// </summary>
        internal static string Liquid_Saltwater_Description {
            get {
                return ResourceManager.GetString("Liquid.Saltwater.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saltwater.
        /// </summary>
        internal static string Liquid_Saltwater_Name {
            get {
                return ResourceManager.GetString("Liquid.Saltwater.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Essential liquid that can freeze, evaporate, and put out fires..
        /// </summary>
        internal static string Liquid_Water_Description {
            get {
                return ResourceManager.GetString("Liquid.Water.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Water.
        /// </summary>
        internal static string Liquid_Water_Name {
            get {
                return ResourceManager.GetString("Liquid.Water.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Infinitely generates the neighboring element until removed..
        /// </summary>
        internal static string Solid_Immovable_Clone_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Clone.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clone.
        /// </summary>
        internal static string Solid_Immovable_Clone_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Clone.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Crystallized, immobile corruption that creates permanent contaminated areas..
        /// </summary>
        internal static string Solid_Immovable_Corruption_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (immovable).
        /// </summary>
        internal static string Solid_Immovable_Corruption_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It will try to consume everything around it. When it has nothing left to feed on, it will explode..
        /// </summary>
        internal static string Solid_Immovable_Devourer_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Devourer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Devourer.
        /// </summary>
        internal static string Solid_Immovable_Devourer_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Devourer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It shifts neighboring elements down..
        /// </summary>
        internal static string Solid_Immovable_DownwardPusher_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DownwardPusher.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downward Pusher.
        /// </summary>
        internal static string Solid_Immovable_DownwardPusher_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DownwardPusher.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryBlackWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryBlackWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryBlackWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryBlackWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryBlueWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryBlueWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryBlueWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryBlueWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryBrownWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryBrownWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryBrownWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryBrownWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryCyanWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryCyanWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryCyanWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryCyanWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryGreenWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryGreenWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryGreenWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryGreenWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryOrangeWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryOrangeWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryOrangeWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryOrangeWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryRedWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryRedWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryRedWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryRedWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dry sponge that absorbs liquids and is very flammable..
        /// </summary>
        internal static string Solid_Immovable_DrySponge_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DrySponge.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sponge (dry).
        /// </summary>
        internal static string Solid_Immovable_DrySponge_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DrySponge.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryVioletWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryVioletWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryVioletWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryVioletWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryWhiteWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryWhiteWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryWhiteWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryWhiteWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryYellowWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryYellowWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_DryYellowWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DryYellowWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Device that cools all nearby elements..
        /// </summary>
        internal static string Solid_Immovable_Freezer_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Freezer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Freezer.
        /// </summary>
        internal static string Solid_Immovable_Freezer_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Freezer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transparent and fragile material, breaks with heat or impact..
        /// </summary>
        internal static string Solid_Immovable_Glass_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Glass.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Glass.
        /// </summary>
        internal static string Solid_Immovable_Glass_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Glass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bright yellow, soft, and malleable metal..
        /// </summary>
        internal static string Solid_Immovable_Gold_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Gold.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gold.
        /// </summary>
        internal static string Solid_Immovable_Gold_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Gold.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Device that heats all nearby elements..
        /// </summary>
        internal static string Solid_Immovable_Heater_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Heater.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Heater.
        /// </summary>
        internal static string Solid_Immovable_Heater_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Heater.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Strong metal, resists fire but melts in lava..
        /// </summary>
        internal static string Solid_Immovable_Iron_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Iron.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iron.
        /// </summary>
        internal static string Solid_Immovable_Iron_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Iron.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fixed, sturdy lamp used for decoration..
        /// </summary>
        internal static string Solid_Immovable_Lamp_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Lamp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lamp.
        /// </summary>
        internal static string Solid_Immovable_Lamp_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Lamp.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shifts neighboring elements to the left..
        /// </summary>
        internal static string Solid_Immovable_LeftwardPusher_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.LeftwardPusher.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Leftward Pusher.
        /// </summary>
        internal static string Solid_Immovable_LeftwardPusher_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.LeftwardPusher.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_Moss_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Moss.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_Moss_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Moss.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Decorative and functional block, flammable, used in mobile constructions..
        /// </summary>
        internal static string Solid_Immovable_MountingBlock_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.MountingBlock.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mounting Block.
        /// </summary>
        internal static string Solid_Immovable_MountingBlock_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.MountingBlock.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Durable block, ideal for fire-resistant constructions..
        /// </summary>
        internal static string Solid_Immovable_RedBrick_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.RedBrick.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Red Brick.
        /// </summary>
        internal static string Solid_Immovable_RedBrick_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.RedBrick.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shifts neighboring elements to the right..
        /// </summary>
        internal static string Solid_Immovable_RightwardPusher_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.RightwardPusher.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rightward Pusher.
        /// </summary>
        internal static string Solid_Immovable_RightwardPusher_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.RightwardPusher.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Natural, flammable leaf, used for decoration..
        /// </summary>
        internal static string Solid_Immovable_TreeLeaf_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.TreeLeaf.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tree Leaf.
        /// </summary>
        internal static string Solid_Immovable_TreeLeaf_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.TreeLeaf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It moves neighboring elements upward..
        /// </summary>
        internal static string Solid_Immovable_UpwardPusher_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.UpwardPusher.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Upward Pusher.
        /// </summary>
        internal static string Solid_Immovable_UpwardPusher_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.UpwardPusher.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Absorbs and destroys everything it touches..
        /// </summary>
        internal static string Solid_Immovable_Void_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Void.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Void.
        /// </summary>
        internal static string Solid_Immovable_Void_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Void.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solid, impenetrable, and stable barrier..
        /// </summary>
        internal static string Solid_Immovable_Wall_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Wall.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wall.
        /// </summary>
        internal static string Solid_Immovable_Wall_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Wall.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetBlackWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetBlackWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetBlackWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetBlackWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetBlueWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetBlueWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetBlueWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetBlueWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetBrownWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetBrownWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetBrownWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetBrownWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetCyanWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetCyanWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetCyanWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetCyanWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetGreenWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetGreenWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetGreenWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetGreenWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetOrangeWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetOrangeWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetOrangeWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetOrangeWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetRedWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetRedWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetRedWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetRedWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wet sponge, denser and harder to burn. Dries with heat and moves down if dry sponges are below..
        /// </summary>
        internal static string Solid_Immovable_WetSponge_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetSponge.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sponge (wet).
        /// </summary>
        internal static string Solid_Immovable_WetSponge_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetSponge.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetVioletWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetVioletWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetVioletWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetVioletWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetWhiteWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetWhiteWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetWhiteWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetWhiteWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetYellowWool_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetYellowWool.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Immovable_WetYellowWool_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetYellowWool.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Natural, very flammable material, common in constructions..
        /// </summary>
        internal static string Solid_Immovable_Wood_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Wood.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wood.
        /// </summary>
        internal static string Solid_Immovable_Wood_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Wood.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dark gray powder, looks like remains of wood or burnt materials..
        /// </summary>
        internal static string Solid_Movable_Ash_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Ash.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ash.
        /// </summary>
        internal static string Solid_Movable_Ash_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Ash.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Low-power bomb that explodes when hitting other elements..
        /// </summary>
        internal static string Solid_Movable_Bomb_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Bomb.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bomb.
        /// </summary>
        internal static string Solid_Movable_Bomb_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Bomb.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Substance that spreads, contaminates, and destroys the environment continuously..
        /// </summary>
        internal static string Solid_Movable_Corruption_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (movable).
        /// </summary>
        internal static string Solid_Movable_Corruption_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dry, unstable soil, base for vegetation. Turns into mud when in contact with water..
        /// </summary>
        internal static string Solid_Movable_Dirt_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Dirt.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dirt.
        /// </summary>
        internal static string Solid_Movable_Dirt_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Dirt.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Large-radius explosive, only explodes with heat or contact with lava/fire..
        /// </summary>
        internal static string Solid_Movable_Dynamite_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Dynamite.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dynamite.
        /// </summary>
        internal static string Solid_Movable_Dynamite_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Dynamite.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Movable_FertileSoil_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.FertileSoil.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Movable_FertileSoil_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.FertileSoil.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dry grass, very flammable, burns fast and leaves ash..
        /// </summary>
        internal static string Solid_Movable_Grass_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Grass.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grass.
        /// </summary>
        internal static string Solid_Movable_Grass_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Grass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Movable_Gunpowder_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Gunpowder.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Movable_Gunpowder_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Gunpowder.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solid, slippery water, melts easily with heat..
        /// </summary>
        internal static string Solid_Movable_Ice_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Ice.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ice.
        /// </summary>
        internal static string Solid_Movable_Ice_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Ice.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mix of dirt and water, turns into dry dirt when heated..
        /// </summary>
        internal static string Solid_Movable_Mud_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Mud.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mud.
        /// </summary>
        internal static string Solid_Movable_Mud_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Mud.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a White, crystalline powder that dissolves in water..
        /// </summary>
        internal static string Solid_Movable_Salt_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Salt.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salt.
        /// </summary>
        internal static string Solid_Movable_Salt_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Salt.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mineral grains that flow and pile up. Become glass with extreme heat..
        /// </summary>
        internal static string Solid_Movable_Sand_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Sand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sand.
        /// </summary>
        internal static string Solid_Movable_Sand_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Sand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Movable_Sapling_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Sapling.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Movable_Sapling_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Sapling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Movable_Seed_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Seed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Solid_Movable_Seed_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Seed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Snowflakes that melt into water with heat..
        /// </summary>
        internal static string Solid_Movable_Snow_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Snow.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Snow.
        /// </summary>
        internal static string Solid_Movable_Snow_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Snow.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rock that resists impacts, melts into lava with extreme heat or turns into sand with erosion..
        /// </summary>
        internal static string Solid_Movable_Stone_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Stone.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stone.
        /// </summary>
        internal static string Solid_Movable_Stone_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Stone.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Moderate explosive, destroys solids and leaves smoke/fire. Only explodes with heat or contact with lava/fire..
        /// </summary>
        internal static string Solid_Movable_TNT_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.TNT.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TNT.
        /// </summary>
        internal static string Solid_Movable_TNT_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.TNT.Name", resourceCulture);
            }
        }
    }
}
