/*
 * Copyright (C) 2026  Davi "Starciad" Fernandes <davilsfernandes.starciad.comu@gmail.com>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Tools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Tools() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.Localization.Localization.Tools", typeof(Localization_Tools).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use this tool to lower the temperature in an area of the world..
        /// </summary>
        internal static string Environment_Freeze_Description {
            get {
                return ResourceManager.GetString("Environment.Freeze.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Freeze Tool.
        /// </summary>
        internal static string Environment_Freeze_Name {
            get {
                return ResourceManager.GetString("Environment.Freeze.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use this tool to raise the temperature in an area of the world..
        /// </summary>
        internal static string Environment_Heat_Description {
            get {
                return ResourceManager.GetString("Environment.Heat.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Heat Tool.
        /// </summary>
        internal static string Environment_Heat_Name {
            get {
                return ResourceManager.GetString("Environment.Heat.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements black..
        /// </summary>
        internal static string Inks_Black_Description {
            get {
                return ResourceManager.GetString("Inks.Black.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Black Ink.
        /// </summary>
        internal static string Inks_Black_Name {
            get {
                return ResourceManager.GetString("Inks.Black.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements blue..
        /// </summary>
        internal static string Inks_Blue_Description {
            get {
                return ResourceManager.GetString("Inks.Blue.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Blue Ink.
        /// </summary>
        internal static string Inks_Blue_Name {
            get {
                return ResourceManager.GetString("Inks.Blue.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements brown..
        /// </summary>
        internal static string Inks_Brown_Description {
            get {
                return ResourceManager.GetString("Inks.Brown.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brown Ink.
        /// </summary>
        internal static string Inks_Brown_Name {
            get {
                return ResourceManager.GetString("Inks.Brown.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements gray..
        /// </summary>
        internal static string Inks_Gray_Description {
            get {
                return ResourceManager.GetString("Inks.Gray.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gray Ink.
        /// </summary>
        internal static string Inks_Gray_Name {
            get {
                return ResourceManager.GetString("Inks.Gray.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements green..
        /// </summary>
        internal static string Inks_Green_Description {
            get {
                return ResourceManager.GetString("Inks.Green.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Green Ink.
        /// </summary>
        internal static string Inks_Green_Name {
            get {
                return ResourceManager.GetString("Inks.Green.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements orange..
        /// </summary>
        internal static string Inks_Orange_Description {
            get {
                return ResourceManager.GetString("Inks.Orange.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Orange Ink.
        /// </summary>
        internal static string Inks_Orange_Name {
            get {
                return ResourceManager.GetString("Inks.Orange.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements red..
        /// </summary>
        internal static string Inks_Red_Description {
            get {
                return ResourceManager.GetString("Inks.Red.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Red Ink.
        /// </summary>
        internal static string Inks_Red_Name {
            get {
                return ResourceManager.GetString("Inks.Red.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements violet..
        /// </summary>
        internal static string Inks_Violet_Description {
            get {
                return ResourceManager.GetString("Inks.Violet.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Violet Ink.
        /// </summary>
        internal static string Inks_Violet_Name {
            get {
                return ResourceManager.GetString("Inks.Violet.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Painting the elements white will restore their original colors..
        /// </summary>
        internal static string Inks_White_Description {
            get {
                return ResourceManager.GetString("Inks.White.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a White Ink.
        /// </summary>
        internal static string Inks_White_Name {
            get {
                return ResourceManager.GetString("Inks.White.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It allows you to dye the elements yellow..
        /// </summary>
        internal static string Inks_Yellow_Description {
            get {
                return ResourceManager.GetString("Inks.Yellow.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yellow Ink.
        /// </summary>
        internal static string Inks_Yellow_Name {
            get {
                return ResourceManager.GetString("Inks.Yellow.Name", resourceCulture);
            }
        }
    }
}

