//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.ContentBundle.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SLocalization() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.ContentBundle.Localization.SLocalization", typeof(SLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A manifestation of heat and energy, consuming flammable materials rapidly and spreading destruction with intense speed..
        /// </summary>
        internal static string Element_Energy_Fire_Description {
            get {
                return ResourceManager.GetString("Element.Energy.Fire.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fire.
        /// </summary>
        internal static string Element_Energy_Fire_Name {
            get {
                return ResourceManager.GetString("Element.Energy.Fire.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A gaseous version of corruption, it spreads through the air and contaminates everything within its reach, making the environment inhospitable..
        /// </summary>
        internal static string Element_Gas_Corruption_Description {
            get {
                return ResourceManager.GetString("Element.Gas.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (gas).
        /// </summary>
        internal static string Element_Gas_Corruption_Name {
            get {
                return ResourceManager.GetString("Element.Gas.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A byproduct of combustion, it rises slowly, obscuring the air and indicating the presence of fire or burning..
        /// </summary>
        internal static string Element_Gas_Smoke_Description {
            get {
                return ResourceManager.GetString("Element.Gas.Smoke.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Smoke.
        /// </summary>
        internal static string Element_Gas_Smoke_Name {
            get {
                return ResourceManager.GetString("Element.Gas.Smoke.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hot water vapor that rises rapidly and disperses into the air, signaling latent heat in the environment..
        /// </summary>
        internal static string Element_Gas_Steam_Description {
            get {
                return ResourceManager.GetString("Element.Gas.Steam.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Steam.
        /// </summary>
        internal static string Element_Gas_Steam_Name {
            get {
                return ResourceManager.GetString("Element.Gas.Steam.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A highly corrosive liquid that dissolves various materials on contact with extreme speed..
        /// </summary>
        internal static string Element_Liquid_Acid_Description {
            get {
                return ResourceManager.GetString("Element.Liquid.Acid.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acid.
        /// </summary>
        internal static string Element_Liquid_Acid_Name {
            get {
                return ResourceManager.GetString("Element.Liquid.Acid.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Highly contaminating liquid substance, flowing freely and corrupting all matter with which it interacts..
        /// </summary>
        internal static string Element_Liquid_Corruption_Description {
            get {
                return ResourceManager.GetString("Element.Liquid.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (liquid).
        /// </summary>
        internal static string Element_Liquid_Corruption_Name {
            get {
                return ResourceManager.GetString("Element.Liquid.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Molten rock that incinerates almost everything on contact. It cools down into solid stone if exposed to lower temperatures..
        /// </summary>
        internal static string Element_Liquid_Lava_Description {
            get {
                return ResourceManager.GetString("Element.Liquid.Lava.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lava.
        /// </summary>
        internal static string Element_Liquid_Lava_Name {
            get {
                return ResourceManager.GetString("Element.Liquid.Lava.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dynamic fluid that flows freely. Can freeze into ice or evaporate into steam when overheated, extinguishing fire along the way..
        /// </summary>
        internal static string Element_Liquid_Water_Description {
            get {
                return ResourceManager.GetString("Element.Liquid.Water.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Water.
        /// </summary>
        internal static string Element_Liquid_Water_Name {
            get {
                return ResourceManager.GetString("Element.Liquid.Water.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Crystallized and dense form of corruption. Immobile and permanent, it creates irreversible contaminated zones..
        /// </summary>
        internal static string Element_Solid_Immovable_Corruption_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (immovable).
        /// </summary>
        internal static string Element_Solid_Immovable_Corruption_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A transparent yet fragile material, shattering on impact or disintegrating under high temperatures..
        /// </summary>
        internal static string Element_Solid_Immovable_Glass_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Glass.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Glass.
        /// </summary>
        internal static string Element_Solid_Immovable_Glass_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Glass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A strong, iron-based element. It withstands fire but melts into lava under extreme heat..
        /// </summary>
        internal static string Element_Solid_Immovable_Metal_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Metal.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Metal.
        /// </summary>
        internal static string Element_Solid_Immovable_Metal_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Metal.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Functional and decorative block, available in vibrant colors. Flammable, it adds dynamism and aesthetics to mobile constructions..
        /// </summary>
        internal static string Element_Solid_Immovable_MountingBlock_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.MountingBlock.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mounting Block.
        /// </summary>
        internal static string Element_Solid_Immovable_MountingBlock_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.MountingBlock.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Strong and durable block, ideal for fortified constructions, especially due to its fire resistance..
        /// </summary>
        internal static string Element_Solid_Immovable_RedBrick_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.RedBrick.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Red Brick.
        /// </summary>
        internal static string Element_Solid_Immovable_RedBrick_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.RedBrick.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Natural and flammable foliage, common in forest areas. It can be used to decorate and enrich the natural scenery..
        /// </summary>
        internal static string Element_Solid_Immovable_TreeLeaf_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.TreeLeaf.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tree Leaf.
        /// </summary>
        internal static string Element_Solid_Immovable_TreeLeaf_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.TreeLeaf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An impenetrable, solid barrier. Resistant to natural forces and unaffected by other elements..
        /// </summary>
        internal static string Element_Solid_Immovable_Wall_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Wall.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wall.
        /// </summary>
        internal static string Element_Solid_Immovable_Wall_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Wall.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A natural, flammable material often used in constructions. Burns easily when in contact with fire..
        /// </summary>
        internal static string Element_Solid_Immovable_Wood_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Wood.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wood.
        /// </summary>
        internal static string Element_Solid_Immovable_Wood_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Wood.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An unstable substance that spreads and infects corruptible materials, causing unstoppable destruction across the world..
        /// </summary>
        internal static string Element_Solid_Movable_Corruption_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (movable).
        /// </summary>
        internal static string Element_Solid_Movable_Corruption_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dry soil, the foundation for vegetation. Turns into mud when exposed to water..
        /// </summary>
        internal static string Element_Solid_Movable_Dirt_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Dirt.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dirt.
        /// </summary>
        internal static string Element_Solid_Movable_Dirt_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Dirt.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dense and durable rock. Melts into lava under extreme heat and crumbles into sand after prolonged water exposure..
        /// </summary>
        internal static string Element_Solid_Movable_Grass_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Grass.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grass.
        /// </summary>
        internal static string Element_Solid_Movable_Grass_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Grass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Frozen water in solid form. Slippery and melts back into water when exposed to heat..
        /// </summary>
        internal static string Element_Solid_Movable_Ice_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Ice.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ice.
        /// </summary>
        internal static string Element_Solid_Movable_Ice_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Ice.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dense mixture of dirt and water. When heated, it dries up and turns back into dirt..
        /// </summary>
        internal static string Element_Solid_Movable_Mud_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Mud.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mud.
        /// </summary>
        internal static string Element_Solid_Movable_Mud_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Mud.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fine, loose grains that flow and accumulate easily. Under extreme heat, it fuses into glass..
        /// </summary>
        internal static string Element_Solid_Movable_Sand_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Sand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sand.
        /// </summary>
        internal static string Element_Solid_Movable_Sand_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Sand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accumulated ice crystals in light flakes. Melts into water when exposed to heat..
        /// </summary>
        internal static string Element_Solid_Movable_Snow_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Snow.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Snow.
        /// </summary>
        internal static string Element_Solid_Movable_Snow_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Snow.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dense and durable rock. Melts into lava under extreme heat and crumbles into sand after prolonged water exposure..
        /// </summary>
        internal static string Element_Solid_Movable_Stone_Description {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Stone.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stone.
        /// </summary>
        internal static string Element_Solid_Movable_Stone_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Stone.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A portal to the entire catalog of game elements. Here, you can browse, discover, and learn about each available element, exploring its characteristics, behaviors, and interactions..
        /// </summary>
        internal static string GUI_HUD_Button_ItemExplorer_Description {
            get {
                return ResourceManager.GetString("GUI.HUD.Button.ItemExplorer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item Explorer.
        /// </summary>
        internal static string GUI_HUD_Button_ItemExplorer_Title {
            get {
                return ResourceManager.GetString("GUI.HUD.Button.ItemExplorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a And that&apos;s the end....
        /// </summary>
        internal static string GUI_Menu_Credits_Message_Finalization {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Message.Finalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Thanks for Playing!.
        /// </summary>
        internal static string GUI_Menu_Credits_Message_ThankPlayer {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Message.ThankPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To my parents..
        /// </summary>
        internal static string GUI_Menu_Credits_People_Parents {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.People.Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Artists.
        /// </summary>
        internal static string GUI_Menu_Credits_Title_Artists {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Title.Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Composers.
        /// </summary>
        internal static string GUI_Menu_Credits_Title_Composers {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Title.Composers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contributors.
        /// </summary>
        internal static string GUI_Menu_Credits_Title_Contributors {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Title.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Creator.
        /// </summary>
        internal static string GUI_Menu_Credits_Title_Creator {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Title.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Programming.
        /// </summary>
        internal static string GUI_Menu_Credits_Title_Programming {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Title.Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Roles.
        /// </summary>
        internal static string GUI_Menu_Credits_Title_Roles {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Title.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Special Thanks.
        /// </summary>
        internal static string GUI_Menu_Credits_Title_SpecialThanks {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Title.SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tools.
        /// </summary>
        internal static string GUI_Menu_Credits_Title_Tools {
            get {
                return ResourceManager.GetString("GUI.Menu.Credits.Title.Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        internal static string GUI_Menu_Main_Button_Create {
            get {
                return ResourceManager.GetString("GUI.Menu.Main.Button.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credits.
        /// </summary>
        internal static string GUI_Menu_Main_Button_Credits {
            get {
                return ResourceManager.GetString("GUI.Menu.Main.Button.Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        internal static string GUI_Menu_Main_Button_Options {
            get {
                return ResourceManager.GetString("GUI.Menu.Main.Button.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quit.
        /// </summary>
        internal static string GUI_Menu_Main_Button_Quit {
            get {
                return ResourceManager.GetString("GUI.Menu.Main.Button.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        internal static string GUI_Menu_Main_Create {
            get {
                return ResourceManager.GetString("GUI.Menu.Main.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credits.
        /// </summary>
        internal static string GUI_Menu_Main_Credits {
            get {
                return ResourceManager.GetString("GUI.Menu.Main.Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        internal static string GUI_Menu_Main_Options {
            get {
                return ResourceManager.GetString("GUI.Menu.Main.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quit.
        /// </summary>
        internal static string GUI_Menu_Main_Quit {
            get {
                return ResourceManager.GetString("GUI.Menu.Main.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string GUI_Menu_Options_Section_Language {
            get {
                return ResourceManager.GetString("GUI.Menu.Options.Section.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video.
        /// </summary>
        internal static string GUI_Menu_Options_Section_Video {
            get {
                return ResourceManager.GetString("GUI.Menu.Options.Section.Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Borderless.
        /// </summary>
        internal static string GUI_Menu_Options_Section_Video_Borderless {
            get {
                return ResourceManager.GetString("GUI.Menu.Options.Section.Video.Borderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fullscreen.
        /// </summary>
        internal static string GUI_Menu_Options_Section_Video_Fullscreen {
            get {
                return ResourceManager.GetString("GUI.Menu.Options.Section.Video.Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolution.
        /// </summary>
        internal static string GUI_Menu_Options_Section_Video_Resolution {
            get {
                return ResourceManager.GetString("GUI.Menu.Options.Section.Video.Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VSync.
        /// </summary>
        internal static string GUI_Menu_Options_Section_Video_VSync {
            get {
                return ResourceManager.GetString("GUI.Menu.Options.Section.Video.VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OPTIONS.
        /// </summary>
        internal static string GUI_Menu_Options_Title {
            get {
                return ResourceManager.GetString("GUI.Menu.Options.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Energies.
        /// </summary>
        internal static string Item_Category_Energies {
            get {
                return ResourceManager.GetString("Item.Category.Energies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forces of nature in their purest and most dynamic forms. Unpredictable and powerful, they shape and transform their surroundings with intensity, igniting change wherever they go..
        /// </summary>
        internal static string Item_Category_Energies_Description {
            get {
                return ResourceManager.GetString("Item.Category.Energies.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gases.
        /// </summary>
        internal static string Item_Category_Gases {
            get {
                return ResourceManager.GetString("Item.Category.Gases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elusive and ever-shifting, gases drift through the air, expanding without boundaries. Invisible or visible, they can be harmless, suffocating, or even destructive, always moving, always present..
        /// </summary>
        internal static string Item_Category_Gases_Description {
            get {
                return ResourceManager.GetString("Item.Category.Gases.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Liquids.
        /// </summary>
        internal static string Item_Category_Liquids {
            get {
                return ResourceManager.GetString("Item.Category.Liquids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fluid and adaptable, liquids carve their path through the world. Whether calm or chaotic, they flow, fill, and transform, essential to life but also capable of overwhelming destruction..
        /// </summary>
        internal static string Item_Category_Liquids_Description {
            get {
                return ResourceManager.GetString("Item.Category.Liquids.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Powders.
        /// </summary>
        internal static string Item_Category_Powders {
            get {
                return ResourceManager.GetString("Item.Category.Powders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elements with the power to gather and disperse. They shift, settle, and adapt to their environment, demonstrating that even the smallest elements can have a significant impact..
        /// </summary>
        internal static string Item_Category_Powders_Description {
            get {
                return ResourceManager.GetString("Item.Category.Powders.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solids.
        /// </summary>
        internal static string Item_Category_Solids {
            get {
                return ResourceManager.GetString("Item.Category.Solids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The anchors of the world, unyielding and steadfast. Solids provide structure and strength, standing firm against the forces of nature, embodying permanence and resilience..
        /// </summary>
        internal static string Item_Category_Solids_Description {
            get {
                return ResourceManager.GetString("Item.Category.Solids.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Walls.
        /// </summary>
        internal static string Item_Category_Walls {
            get {
                return ResourceManager.GetString("Item.Category.Walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Barriers of purpose, designed to separate and protect. Walls are the silent guardians, creating boundaries that define spaces and safeguard from external forces..
        /// </summary>
        internal static string Item_Category_Walls_Description {
            get {
                return ResourceManager.GetString("Item.Category.Walls.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a False.
        /// </summary>
        internal static string Statements_False {
            get {
                return ResourceManager.GetString("Statements.False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a F.
        /// </summary>
        internal static string Statements_False_Short {
            get {
                return ResourceManager.GetString("Statements.False.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string Statements_No {
            get {
                return ResourceManager.GetString("Statements.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a N.
        /// </summary>
        internal static string Statements_No_Short {
            get {
                return ResourceManager.GetString("Statements.No.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Return.
        /// </summary>
        internal static string Statements_Return {
            get {
                return ResourceManager.GetString("Statements.Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string Statements_Save {
            get {
                return ResourceManager.GetString("Statements.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a True.
        /// </summary>
        internal static string Statements_True {
            get {
                return ResourceManager.GetString("Statements.True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a T.
        /// </summary>
        internal static string Statements_True_Short {
            get {
                return ResourceManager.GetString("Statements.True.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string Statements_Yes {
            get {
                return ResourceManager.GetString("Statements.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y.
        /// </summary>
        internal static string Statements_Yes_Short {
            get {
                return ResourceManager.GetString("Statements.Yes.Short", resourceCulture);
            }
        }
    }
}
