//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.ContentBundle.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SLocalization() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.ContentBundle.Localization.SLocalization", typeof(SLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fire.
        /// </summary>
        internal static string Element_Energy_Fire_Name {
            get {
                return ResourceManager.GetString("Element.Energy.Fire.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (gas).
        /// </summary>
        internal static string Element_Gas_Corruption_Name {
            get {
                return ResourceManager.GetString("Element.Gas.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Smoke.
        /// </summary>
        internal static string Element_Gas_Smoke_Name {
            get {
                return ResourceManager.GetString("Element.Gas.Smoke.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Steam.
        /// </summary>
        internal static string Element_Gas_Steam_Name {
            get {
                return ResourceManager.GetString("Element.Gas.Steam.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acid.
        /// </summary>
        internal static string Element_Liquid_Acid_Name {
            get {
                return ResourceManager.GetString("Element.Liquid.Acid.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (liquid).
        /// </summary>
        internal static string Element_Liquid_Corruption_Name {
            get {
                return ResourceManager.GetString("Element.Liquid.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lava.
        /// </summary>
        internal static string Element_Liquid_Lava_Name {
            get {
                return ResourceManager.GetString("Element.Liquid.Lava.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Water.
        /// </summary>
        internal static string Element_Liquid_Water_Name {
            get {
                return ResourceManager.GetString("Element.Liquid.Water.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (immovable).
        /// </summary>
        internal static string Element_Solid_Immovable_Corruption_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Glass.
        /// </summary>
        internal static string Element_Solid_Immovable_Glass_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Glass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Metal.
        /// </summary>
        internal static string Element_Solid_Immovable_Metal_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Metal.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mounting Block.
        /// </summary>
        internal static string Element_Solid_Immovable_MountingBlock_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.MountingBlock.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Red Brick.
        /// </summary>
        internal static string Element_Solid_Immovable_RedBrick_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.RedBrick.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tree Leaf.
        /// </summary>
        internal static string Element_Solid_Immovable_TreeLeaf_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.TreeLeaf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wall.
        /// </summary>
        internal static string Element_Solid_Immovable_Wall_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Wall.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wood.
        /// </summary>
        internal static string Element_Solid_Immovable_Wood_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Immovable.Wood.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (movable).
        /// </summary>
        internal static string Element_Solid_Movable_Corruption_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dirt.
        /// </summary>
        internal static string Element_Solid_Movable_Dirt_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Dirt.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grass.
        /// </summary>
        internal static string Element_Solid_Movable_Grass_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Grass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ice.
        /// </summary>
        internal static string Element_Solid_Movable_Ice_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Ice.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mud.
        /// </summary>
        internal static string Element_Solid_Movable_Mud_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Mud.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sand.
        /// </summary>
        internal static string Element_Solid_Movable_Sand_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Sand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Snow.
        /// </summary>
        internal static string Element_Solid_Movable_Snow_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Snow.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stone.
        /// </summary>
        internal static string Element_Solid_Movable_Stone_Name {
            get {
                return ResourceManager.GetString("Element.Solid.Movable.Stone.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        internal static string GUI_Menu_MainMenu_Create {
            get {
                return ResourceManager.GetString("GUI.Menu.MainMenu.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credits.
        /// </summary>
        internal static string GUI_Menu_MainMenu_Credits {
            get {
                return ResourceManager.GetString("GUI.Menu.MainMenu.Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        internal static string GUI_Menu_MainMenu_Options {
            get {
                return ResourceManager.GetString("GUI.Menu.MainMenu.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Play.
        /// </summary>
        internal static string GUI_Menu_MainMenu_Play {
            get {
                return ResourceManager.GetString("GUI.Menu.MainMenu.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quit.
        /// </summary>
        internal static string GUI_Menu_MainMenu_Quit {
            get {
                return ResourceManager.GetString("GUI.Menu.MainMenu.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cursor.
        /// </summary>
        internal static string GUI_Menu_OptionsMenu_Section_Cursor {
            get {
                return ResourceManager.GetString("GUI.Menu.OptionsMenu.Section.Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General.
        /// </summary>
        internal static string GUI_Menu_OptionsMenu_Section_General {
            get {
                return ResourceManager.GetString("GUI.Menu.OptionsMenu.Section.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string GUI_Menu_OptionsMenu_Section_Language {
            get {
                return ResourceManager.GetString("GUI.Menu.OptionsMenu.Section.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video.
        /// </summary>
        internal static string GUI_Menu_OptionsMenu_Section_Video {
            get {
                return ResourceManager.GetString("GUI.Menu.OptionsMenu.Section.Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Volume.
        /// </summary>
        internal static string GUI_Menu_OptionsMenu_Section_Volume {
            get {
                return ResourceManager.GetString("GUI.Menu.OptionsMenu.Section.Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OPTIONS.
        /// </summary>
        internal static string GUI_Menu_OptionsMenu_Title {
            get {
                return ResourceManager.GetString("GUI.Menu.OptionsMenu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Energies.
        /// </summary>
        internal static string Item_Category_Energies {
            get {
                return ResourceManager.GetString("Item.Category.Energies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gases.
        /// </summary>
        internal static string Item_Category_Gases {
            get {
                return ResourceManager.GetString("Item.Category.Gases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Liquids.
        /// </summary>
        internal static string Item_Category_Liquids {
            get {
                return ResourceManager.GetString("Item.Category.Liquids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Powders.
        /// </summary>
        internal static string Item_Category_Powders {
            get {
                return ResourceManager.GetString("Item.Category.Powders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solids.
        /// </summary>
        internal static string Item_Category_Solids {
            get {
                return ResourceManager.GetString("Item.Category.Solids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Walls.
        /// </summary>
        internal static string Item_Category_Walls {
            get {
                return ResourceManager.GetString("Item.Category.Walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a False.
        /// </summary>
        internal static string Statements_False {
            get {
                return ResourceManager.GetString("Statements.False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a F.
        /// </summary>
        internal static string Statements_False_Short {
            get {
                return ResourceManager.GetString("Statements.False.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string Statements_No {
            get {
                return ResourceManager.GetString("Statements.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a N.
        /// </summary>
        internal static string Statements_No_Short {
            get {
                return ResourceManager.GetString("Statements.No.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Return.
        /// </summary>
        internal static string Statements_Return {
            get {
                return ResourceManager.GetString("Statements.Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string Statements_Save {
            get {
                return ResourceManager.GetString("Statements.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a True.
        /// </summary>
        internal static string Statements_True {
            get {
                return ResourceManager.GetString("Statements.True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a T.
        /// </summary>
        internal static string Statements_True_Short {
            get {
                return ResourceManager.GetString("Statements.True.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string Statements_Yes {
            get {
                return ResourceManager.GetString("Statements.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y.
        /// </summary>
        internal static string Statements_Yes_Short {
            get {
                return ResourceManager.GetString("Statements.Yes.Short", resourceCulture);
            }
        }
    }
}
