//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.ContentBundle.Localization.GUIs {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SLocalization_GUIs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SLocalization_GUIs() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.ContentBundle.Localization.GUIs.SLocalization.GUIs", typeof(SLocalization_GUIs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closes the current menu..
        /// </summary>
        internal static string Button_Exit_Description {
            get {
                return ResourceManager.GetString("Button.Exit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modifies the world&apos;s environmental properties, including weather, temperature, and other factors..
        /// </summary>
        internal static string HUD_Button_EnvironmentSettings_Description {
            get {
                return ResourceManager.GetString("HUD.Button.EnvironmentSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Environment Settings.
        /// </summary>
        internal static string HUD_Button_EnvironmentSettings_Name {
            get {
                return ResourceManager.GetString("HUD.Button.EnvironmentSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clears all content from the map, including elements, entities, and decorations, restoring it to an empty initial state..
        /// </summary>
        internal static string HUD_Button_EraseEverything_Description {
            get {
                return ResourceManager.GetString("HUD.Button.EraseEverything.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erase Everything.
        /// </summary>
        internal static string HUD_Button_EraseEverything_Name {
            get {
                return ResourceManager.GetString("HUD.Button.EraseEverything.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turns the current pen into an eraser, allowing you to directly remove content from the canvas..
        /// </summary>
        internal static string HUD_Button_Eraser_Description {
            get {
                return ResourceManager.GetString("HUD.Button.Eraser.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Eraser.
        /// </summary>
        internal static string HUD_Button_Eraser_Name {
            get {
                return ResourceManager.GetString("HUD.Button.Eraser.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opens the game&apos;s main menu to access settings and other options..
        /// </summary>
        internal static string HUD_Button_GameMenu_Description {
            get {
                return ResourceManager.GetString("HUD.Button.GameMenu.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Game Menu.
        /// </summary>
        internal static string HUD_Button_GameMenu_Name {
            get {
                return ResourceManager.GetString("HUD.Button.GameMenu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a View general information and statistics related to your world..
        /// </summary>
        internal static string HUD_Button_Information_Description {
            get {
                return ResourceManager.GetString("HUD.Button.Information.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Information.
        /// </summary>
        internal static string HUD_Button_Information_Name {
            get {
                return ResourceManager.GetString("HUD.Button.Information.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A portal to the entire catalog of game elements. Here, you can browse, discover, and learn about each available element, exploring its characteristics, behaviors, and interactions..
        /// </summary>
        internal static string HUD_Button_ItemExplorer_Description {
            get {
                return ResourceManager.GetString("HUD.Button.ItemExplorer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item Explorer.
        /// </summary>
        internal static string HUD_Button_ItemExplorer_Name {
            get {
                return ResourceManager.GetString("HUD.Button.ItemExplorer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pauses or resumes the ongoing simulation..
        /// </summary>
        internal static string HUD_Button_PauseSimulation_Description {
            get {
                return ResourceManager.GetString("HUD.Button.PauseSimulation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pause Simulation.
        /// </summary>
        internal static string HUD_Button_PauseSimulation_Name {
            get {
                return ResourceManager.GetString("HUD.Button.PauseSimulation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjusts the pen settings, modifying how it interacts with the world&apos;s canvas..
        /// </summary>
        internal static string HUD_Button_PenSettings_Description {
            get {
                return ResourceManager.GetString("HUD.Button.PenSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pen Settings.
        /// </summary>
        internal static string HUD_Button_PenSettings_Name {
            get {
                return ResourceManager.GetString("HUD.Button.PenSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reloads a previously loaded simulation, reverting any changes made. If no simulation is loaded, clears the map, leaving the canvas empty..
        /// </summary>
        internal static string HUD_Button_ReloadSimulation_Description {
            get {
                return ResourceManager.GetString("HUD.Button.ReloadSimulation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reload Simulation.
        /// </summary>
        internal static string HUD_Button_ReloadSimulation_Name {
            get {
                return ResourceManager.GetString("HUD.Button.ReloadSimulation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opens the menu to manage simulation and world saving..
        /// </summary>
        internal static string HUD_Button_SaveMenu_Description {
            get {
                return ResourceManager.GetString("HUD.Button.SaveMenu.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Menu.
        /// </summary>
        internal static string HUD_Button_SaveMenu_Name {
            get {
                return ResourceManager.GetString("HUD.Button.SaveMenu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjusts general and systematic settings for the world..
        /// </summary>
        internal static string HUD_Button_WorldSettings_Description {
            get {
                return ResourceManager.GetString("HUD.Button.WorldSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a World Settings.
        /// </summary>
        internal static string HUD_Button_WorldSettings_Name {
            get {
                return ResourceManager.GetString("HUD.Button.WorldSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jump to afternoon (03:00 PM)..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Afternoon_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Afternoon.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Afternoon.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Afternoon_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Afternoon.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jump to dawn (06:00 AM)..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Dawn_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Dawn.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dawn.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Dawn_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Dawn.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jump to dusk (06:00 PM)..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Dusk_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Dusk.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dusk.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Dusk_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Dusk.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jump to evening (09:00 PM)..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Evening_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Evening.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Evening.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Evening_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Evening.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jump to midnight (00:00)..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Midnight_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Midnight.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Midnight.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Midnight_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Midnight.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jump to morning (09:00 AM)..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Morning_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Morning.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Morning.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Morning_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Morning.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jump to noon (12:00 PM)..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Noon_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Noon.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Noon.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Button_Noon_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Button.Noon.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Time.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_Time_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.Time.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disable the time progression, freezing the current time..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_TimeState_Button_Disable_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.TimeState.Button.Disable.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable the time progression, resuming the natural time flow..
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_TimeState_Button_Enable_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.TimeState.Button.Enable.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a State.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Section_TimeState_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Section.TimeState.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Environment Settings.
        /// </summary>
        internal static string HUD_Complements_EnvironmentSettings_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.EnvironmentSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background Elements.
        /// </summary>
        internal static string HUD_Complements_Information_Field_BackgroundElements {
            get {
                return ResourceManager.GetString("HUD.Complements.Information.Field.BackgroundElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foreground Elements.
        /// </summary>
        internal static string HUD_Complements_Information_Field_ForegroundElements {
            get {
                return ResourceManager.GetString("HUD.Complements.Information.Field.ForegroundElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Information.
        /// </summary>
        internal static string HUD_Complements_Information_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.Information.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item Explorer.
        /// </summary>
        internal static string HUD_Complements_ItemExplorer_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.ItemExplorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brush size is set to {0}..
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_BrushSize_Button_Slider_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.BrushSize.Button.Slider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brush Size.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_BrushSize_Button_Slider_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.BrushSize.Button.Slider.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brush Size.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_BrushSize_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.BrushSize.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The back layer of the world is used for item placement..
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Layer_Button_Back_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Layer.Button.Back.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background Layer.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Layer_Button_Back_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Layer.Button.Back.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The front layer of the world is used for item placement..
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Layer_Button_Front_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Layer.Button.Front.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foreground Layer.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Layer_Button_Front_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Layer.Button.Front.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Layer.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Layer_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Layer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The pen shape becomes a circle..
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Shape_Button_Circle_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Shape.Button.Circle.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Circle Shape.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Shape_Button_Circle_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Shape.Button.Circle.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The pen shape becomes a square..
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Shape_Button_Square_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Shape.Button.Square.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Square Shape.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Shape_Button_Square_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Shape.Button.Square.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The pen shape becomes a triangle..
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Shape_Button_Triangle_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Shape.Button.Triangle.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Triangle Shape.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Shape_Button_Triangle_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Shape.Button.Triangle.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shape.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Shape_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Shape.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tool.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Section_Tool_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Section.Tool.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pen Settings.
        /// </summary>
        internal static string HUD_Complements_PenSettings_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.PenSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saves the current state of the world to a file on the computer for later access. If a file with the specified name already exists, it will be overwritten with the current world&apos;s data..
        /// </summary>
        internal static string HUD_Complements_SaveSettings_Button_Save_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.SaveSettings.Button.Save.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string HUD_Complements_SaveSettings_Section_Description_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.SaveSettings.Section.Description.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string HUD_Complements_SaveSettings_Section_Name_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.SaveSettings.Section.Name.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Thumbnail.
        /// </summary>
        internal static string HUD_Complements_SaveSettings_Section_Thumbnail_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.SaveSettings.Section.Thumbnail.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Settings.
        /// </summary>
        internal static string HUD_Complements_SaveSettings_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.SaveSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 240x138 - Designed for expansive gameplay areas. May impact performance on lower-end systems..
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_Large_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.Large.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Large.
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_Large_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.Large.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 120x69 - Balanced for most gameplay scenarios..
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_Medium_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.Medium.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medium.
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_Medium_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.Medium.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 160x92 - Provides ample space for exploration..
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_MediumLarge_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.MediumLarge.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medium Large.
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_MediumLarge_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.MediumLarge.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 80x46 - Allows limited free movement..
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_MediumSmall_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.MediumSmall.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medium Small.
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_MediumSmall_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.MediumSmall.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 40x23 - Fits entirely within the player&apos;s camera..
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_Small_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.Small.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Small.
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_Small_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.Small.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The size of the world will have the dimensions 320x184 - Best for epic-scale worlds. May impact performance on lower-end systems..
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_VeryLarge_Description {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.VeryLarge.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Very Large.
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Button_VeryLarge_Name {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Button.VeryLarge.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sizes.
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Section_Size_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Section.Size.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a World Settings.
        /// </summary>
        internal static string HUD_Complements_WorldSettings_Title {
            get {
                return ResourceManager.GetString("HUD.Complements.WorldSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a And that&apos;s the end....
        /// </summary>
        internal static string Menu_Credits_Message_Finalization {
            get {
                return ResourceManager.GetString("Menu.Credits.Message.Finalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Thanks for Playing!.
        /// </summary>
        internal static string Menu_Credits_Message_ThankPlayer {
            get {
                return ResourceManager.GetString("Menu.Credits.Message.ThankPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To my parents..
        /// </summary>
        internal static string Menu_Credits_People_Parents {
            get {
                return ResourceManager.GetString("Menu.Credits.People.Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Artists.
        /// </summary>
        internal static string Menu_Credits_Title_Artists {
            get {
                return ResourceManager.GetString("Menu.Credits.Title.Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Composers.
        /// </summary>
        internal static string Menu_Credits_Title_Composers {
            get {
                return ResourceManager.GetString("Menu.Credits.Title.Composers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contributors.
        /// </summary>
        internal static string Menu_Credits_Title_Contributors {
            get {
                return ResourceManager.GetString("Menu.Credits.Title.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Creator.
        /// </summary>
        internal static string Menu_Credits_Title_Creator {
            get {
                return ResourceManager.GetString("Menu.Credits.Title.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Programming.
        /// </summary>
        internal static string Menu_Credits_Title_Programming {
            get {
                return ResourceManager.GetString("Menu.Credits.Title.Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Roles.
        /// </summary>
        internal static string Menu_Credits_Title_Roles {
            get {
                return ResourceManager.GetString("Menu.Credits.Title.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Special Thanks.
        /// </summary>
        internal static string Menu_Credits_Title_SpecialThanks {
            get {
                return ResourceManager.GetString("Menu.Credits.Title.SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tools.
        /// </summary>
        internal static string Menu_Credits_Title_Tools {
            get {
                return ResourceManager.GetString("Menu.Credits.Title.Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        internal static string Menu_Main_Button_Create {
            get {
                return ResourceManager.GetString("Menu.Main.Button.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credits.
        /// </summary>
        internal static string Menu_Main_Button_Credits {
            get {
                return ResourceManager.GetString("Menu.Main.Button.Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        internal static string Menu_Main_Button_Options {
            get {
                return ResourceManager.GetString("Menu.Main.Button.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Play.
        /// </summary>
        internal static string Menu_Main_Button_Play {
            get {
                return ResourceManager.GetString("Menu.Main.Button.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quit.
        /// </summary>
        internal static string Menu_Main_Button_Quit {
            get {
                return ResourceManager.GetString("Menu.Main.Button.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string Menu_Options_Section_Language {
            get {
                return ResourceManager.GetString("Menu.Options.Section.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video.
        /// </summary>
        internal static string Menu_Options_Section_Video {
            get {
                return ResourceManager.GetString("Menu.Options.Section.Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Borderless.
        /// </summary>
        internal static string Menu_Options_Section_Video_Borderless {
            get {
                return ResourceManager.GetString("Menu.Options.Section.Video.Borderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fullscreen.
        /// </summary>
        internal static string Menu_Options_Section_Video_Fullscreen {
            get {
                return ResourceManager.GetString("Menu.Options.Section.Video.Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolution.
        /// </summary>
        internal static string Menu_Options_Section_Video_Resolution {
            get {
                return ResourceManager.GetString("Menu.Options.Section.Video.Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VSync.
        /// </summary>
        internal static string Menu_Options_Section_Video_VSync {
            get {
                return ResourceManager.GetString("Menu.Options.Section.Video.VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OPTIONS.
        /// </summary>
        internal static string Menu_Options_Title {
            get {
                return ResourceManager.GetString("Menu.Options.Title", resourceCulture);
            }
        }
    }
}
