//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Catalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Catalog() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.Core.Localization.Localization.Catalog", typeof(Localization_Catalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All living beings that inhabit the world..
        /// </summary>
        internal static string Category_Actors_Description {
            get {
                return ResourceManager.GetString("Category.Actors.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Actors.
        /// </summary>
        internal static string Category_Actors_Name {
            get {
                return ResourceManager.GetString("Category.Actors.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All elements used in different activities, from simple to complex..
        /// </summary>
        internal static string Category_Elements_Description {
            get {
                return ResourceManager.GetString("Category.Elements.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elements.
        /// </summary>
        internal static string Category_Elements_Name {
            get {
                return ResourceManager.GetString("Category.Elements.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tools that add extra features and allow new changes in the world..
        /// </summary>
        internal static string Category_Tools_Description {
            get {
                return ResourceManager.GetString("Category.Tools.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tools.
        /// </summary>
        internal static string Category_Tools_Name {
            get {
                return ResourceManager.GetString("Category.Tools.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fantastic and curious creatures that may inhabit the world..
        /// </summary>
        internal static string Subcategory_Actors_Creatures_Description {
            get {
                return ResourceManager.GetString("Subcategory.Actors.Creatures.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Creatures.
        /// </summary>
        internal static string Subcategory_Actors_Creatures_Name {
            get {
                return ResourceManager.GetString("Subcategory.Actors.Creatures.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pure, dynamic forces of nature. Unpredictable and strong, they quickly change their surroundings..
        /// </summary>
        internal static string Subcategory_Elements_Energies_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Energies.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Energies.
        /// </summary>
        internal static string Subcategory_Elements_Energies_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Energies.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Explosives are made to cause strong reactions, releasing energy, heat, and debris with high destructive power..
        /// </summary>
        internal static string Subcategory_Elements_Explosives_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Explosives.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Explosives.
        /// </summary>
        internal static string Subcategory_Elements_Explosives_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Explosives.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gases move freely in the air, visible or not, and can be harmless, suffocating, or destructive..
        /// </summary>
        internal static string Subcategory_Elements_Gases_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Gases.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gases.
        /// </summary>
        internal static string Subcategory_Elements_Gases_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Gases.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Liquids are adaptable and essential for life. They flow, fill spaces, and can be calm or destructive..
        /// </summary>
        internal static string Subcategory_Elements_Liquids_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Liquids.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Liquids.
        /// </summary>
        internal static string Subcategory_Elements_Liquids_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Liquids.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Powders can gather or spread, adapting to the environment and showing that small things can have a big impact..
        /// </summary>
        internal static string Subcategory_Elements_Powders_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Powders.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Powders.
        /// </summary>
        internal static string Subcategory_Elements_Powders_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Powders.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solids are strong and stable, giving structure and resisting natural forces..
        /// </summary>
        internal static string Subcategory_Elements_Solids_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Solids.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solids.
        /// </summary>
        internal static string Subcategory_Elements_Solids_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Solids.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unique elements with special functions, different from powders, liquids, gases, or solids..
        /// </summary>
        internal static string Subcategory_Elements_Specials_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Specials.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Specials.
        /// </summary>
        internal static string Subcategory_Elements_Specials_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Specials.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Special elements that automate tasks and help with different creations..
        /// </summary>
        internal static string Subcategory_Elements_Technologies_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Technologies.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Technologies.
        /// </summary>
        internal static string Subcategory_Elements_Technologies_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Technologies.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Natural elements that bring life to the world..
        /// </summary>
        internal static string Subcategory_Elements_Vegetation_Description {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Vegetation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vegetation.
        /// </summary>
        internal static string Subcategory_Elements_Vegetation_Name {
            get {
                return ResourceManager.GetString("Subcategory.Elements.Vegetation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tools to interact with and change the environment..
        /// </summary>
        internal static string Subcategory_Tools_Environment_Description {
            get {
                return ResourceManager.GetString("Subcategory.Tools.Environment.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Environment.
        /// </summary>
        internal static string Subcategory_Tools_Environment_Name {
            get {
                return ResourceManager.GetString("Subcategory.Tools.Environment.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tools that grant you the ability to dye elements of the world..
        /// </summary>
        internal static string Subcategory_Tools_Inks_Description {
            get {
                return ResourceManager.GetString("Subcategory.Tools.Inks.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inks.
        /// </summary>
        internal static string Subcategory_Tools_Inks_Name {
            get {
                return ResourceManager.GetString("Subcategory.Tools.Inks.Name", resourceCulture);
            }
        }
    }
}
