namespace StardustSandbox.Enums.Elements
{
    public enum ElementIndex : sbyte
    {
        None = -1,

        Dirt,
        Mud,
        Water,
        Stone,
        Grass,
        Ice,
        Sand,
        Snow,
        MovableCorruption,
        Lava,
        Acid,
        Glass,
        Iron,
        Wall,
        Wood,
        GasCorruption,
        LiquidCorruption,
        ImmovableCorruption,
        Steam,
        Smoke,
        RedBrick,
        TreeLeaf,
        MountingBlock,
        Fire,
        Lamp,
        Void,
        Clone,
        Oil,
        Salt,
        Saltwater,
        Bomb,
        Dynamite,
        Tnt,
        DrySponge,
        WetSponge,
        Gold,
        Heater,
        Freezer,
        Ash,
        AntiCorruption,
        Devourer,
        UpwardPusher,
        RightwardPusher,
        DownwardPusher,
        LeftwardPusher,
        Cloud,
        ChargedCloud,

        Length,
    }
}
