namespace StardustSandbox.Enums.Elements
{
    public enum ElementIndex : sbyte
    {
        None = -1,

        Dirt = 0,
        Mud = 1,
        Water = 2,
        Stone = 3,
        Grass = 4,
        Ice = 5,
        Sand = 6,
        Snow = 7,
        MovableCorruption = 8,
        Lava = 9,
        Acid = 10,
        Glass = 11,
        Iron = 12,
        Wall = 13,
        Wood = 14,
        GasCorruption = 15,
        LiquidCorruption = 16,
        ImmovableCorruption = 17,
        Steam = 18,
        Smoke = 19,
        RedBrick = 20,
        TreeLeaf = 21,
        MountingBlock = 22,
        Fire = 23,
        Lamp = 24,
        Void = 25,
        Clone = 26,
        Oil = 27,
        Salt = 28,
        Saltwater = 29,
        Bomb = 30,
        Dynamite = 31,
        Tnt = 32,
        DrySponge = 33,
        WetSponge = 34,
        Gold = 35,
        Heater = 36,
        Freezer = 37,
        Ash = 38,
        AntiCorruption = 39,
        Devourer = 40,

        UpwardPusher = 41,
        RightwardPusher = 42,
        DownwardPusher = 43,
        LeftwardPusher = 44,

        Cloud = 45,
        ChargedCloud = 46,
        LightningHead = 47,
        LightningBody = 48,

        DryBlackWool = 49,
        DryWhiteWool = 50,
        DryRedWool = 51,
        DryOrangeWool = 52,
        DryYellowWool = 53,
        DryGreenWool = 54,
        DryGrayWool = 55,
        DryBlueWool = 56,
        DryVioletWool = 57,
        DryBrownWool = 58,

        WetBlackWool = 59,
        WetWhiteWool = 60,
        WetRedWool = 61,
        WetOrangeWool = 62,
        WetYellowWool = 63,
        WetGreenWool = 64,
        WetGrayWool = 65,
        WetBlueWool = 66,
        WetVioletWool = 67,
        WetBrownWool = 68,

        FertileSoil = 69,
        Seed = 70,
        Sapling = 71,
        Moss = 72,
        Gunpowder = 73,
        LiquefiedPetroleumGas = 74,
        Obsidian = 75,

        BlackPaint = 76,
        WhitePaint = 77,
        RedPaint = 78,
        OrangePaint = 79,
        YellowPaint = 80,
        GreenPaint = 81,
        BluePaint = 82,
        GrayPaint = 83,
        VioletPaint = 84,
        BrownPaint = 85,

        Mercury = 86,
    }
}
