//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardustSandbox.ContentBundle.Localization.Elements {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SLocalization_Elements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SLocalization_Elements() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardustSandbox.ContentBundle.Localization.Elements.SLocalization.Elements", typeof(SLocalization_Elements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A manifestation of heat and energy, consuming flammable materials rapidly and spreading destruction with intense speed..
        /// </summary>
        internal static string Energy_Fire_Description {
            get {
                return ResourceManager.GetString("Energy.Fire.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fire.
        /// </summary>
        internal static string Energy_Fire_Name {
            get {
                return ResourceManager.GetString("Energy.Fire.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A gaseous version of corruption, it spreads through the air and contaminates everything within its reach, making the environment inhospitable..
        /// </summary>
        internal static string Gas_Corruption_Description {
            get {
                return ResourceManager.GetString("Gas.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (gas).
        /// </summary>
        internal static string Gas_Corruption_Name {
            get {
                return ResourceManager.GetString("Gas.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A byproduct of combustion, it rises slowly, obscuring the air and indicating the presence of fire or burning..
        /// </summary>
        internal static string Gas_Smoke_Description {
            get {
                return ResourceManager.GetString("Gas.Smoke.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Smoke.
        /// </summary>
        internal static string Gas_Smoke_Name {
            get {
                return ResourceManager.GetString("Gas.Smoke.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hot water vapor that rises rapidly and disperses into the air..
        /// </summary>
        internal static string Gas_Steam_Description {
            get {
                return ResourceManager.GetString("Gas.Steam.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Steam.
        /// </summary>
        internal static string Gas_Steam_Name {
            get {
                return ResourceManager.GetString("Gas.Steam.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A highly corrosive liquid that dissolves various materials on contact with extreme speed..
        /// </summary>
        internal static string Liquid_Acid_Description {
            get {
                return ResourceManager.GetString("Liquid.Acid.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acid.
        /// </summary>
        internal static string Liquid_Acid_Name {
            get {
                return ResourceManager.GetString("Liquid.Acid.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Highly contaminating liquid substance, flowing freely and corrupting all matter with which it interacts..
        /// </summary>
        internal static string Liquid_Corruption_Description {
            get {
                return ResourceManager.GetString("Liquid.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (liquid).
        /// </summary>
        internal static string Liquid_Corruption_Name {
            get {
                return ResourceManager.GetString("Liquid.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Molten rock that incinerates almost everything on contact. It cools in the element that originated it if exposed to lower temperatures..
        /// </summary>
        internal static string Liquid_Lava_Description {
            get {
                return ResourceManager.GetString("Liquid.Lava.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lava.
        /// </summary>
        internal static string Liquid_Lava_Name {
            get {
                return ResourceManager.GetString("Liquid.Lava.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dark and thick, highly flammable liquid. It has a relatively low density..
        /// </summary>
        internal static string Liquid_Oil_Description {
            get {
                return ResourceManager.GetString("Liquid.Oil.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oil.
        /// </summary>
        internal static string Liquid_Oil_Name {
            get {
                return ResourceManager.GetString("Liquid.Oil.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A slightly blue and translucent liquid with particles of salt floating in its composition..
        /// </summary>
        internal static string Liquid_Saltwater_Description {
            get {
                return ResourceManager.GetString("Liquid.Saltwater.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saltwater.
        /// </summary>
        internal static string Liquid_Saltwater_Name {
            get {
                return ResourceManager.GetString("Liquid.Saltwater.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Essential and fluid liquid, with dynamic behavior. It can be frozen or evaporated. It can put out fires along the way..
        /// </summary>
        internal static string Liquid_Water_Description {
            get {
                return ResourceManager.GetString("Liquid.Water.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Water.
        /// </summary>
        internal static string Liquid_Water_Name {
            get {
                return ResourceManager.GetString("Liquid.Water.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An element that, upon contact with a neighboring element, will generate it infinitely until the cloner is destroyed or removed..
        /// </summary>
        internal static string Solid_Immovable_Clone_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Clone.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clone.
        /// </summary>
        internal static string Solid_Immovable_Clone_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Clone.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Crystallized and dense form of corruption. Immobile and permanent, it creates irreversible contaminated zones..
        /// </summary>
        internal static string Solid_Immovable_Corruption_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (immovable).
        /// </summary>
        internal static string Solid_Immovable_Corruption_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dry sponge that can absorb liquids around it. It is highly flammable..
        /// </summary>
        internal static string Solid_Immovable_DrySponge_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.DrySponge.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sponge (dry).
        /// </summary>
        internal static string Solid_Immovable_DrySponge_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.DrySponge.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A specialized device that consistently cools all nearby elements..
        /// </summary>
        internal static string Solid_Immovable_Freezer_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Freezer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Freezer.
        /// </summary>
        internal static string Solid_Immovable_Freezer_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Freezer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A transparent yet fragile material, shattering on impact or disintegrating under high temperatures..
        /// </summary>
        internal static string Solid_Immovable_Glass_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Glass.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Glass.
        /// </summary>
        internal static string Solid_Immovable_Glass_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Glass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A bright yellow, soft, and malleable metal..
        /// </summary>
        internal static string Solid_Immovable_Gold_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Gold.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gold.
        /// </summary>
        internal static string Solid_Immovable_Gold_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Gold.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A specialized device that consistently heats all nearby elements..
        /// </summary>
        internal static string Solid_Immovable_Heater_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Heater.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Heater.
        /// </summary>
        internal static string Solid_Immovable_Heater_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Heater.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A strong, iron-based element. It withstands fire but melts into lava under extreme heat..
        /// </summary>
        internal static string Solid_Immovable_Iron_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Iron.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iron.
        /// </summary>
        internal static string Solid_Immovable_Iron_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Iron.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A light source capable of illuminating surroundings and highlighting details. Durable and fixed, it is perfect for environments that require constant clarity..
        /// </summary>
        internal static string Solid_Immovable_Lamp_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Lamp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lamp.
        /// </summary>
        internal static string Solid_Immovable_Lamp_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Lamp.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Functional and decorative block, available in vibrant colors. Flammable, it adds dynamism and aesthetics to mobile constructions..
        /// </summary>
        internal static string Solid_Immovable_MountingBlock_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.MountingBlock.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mounting Block.
        /// </summary>
        internal static string Solid_Immovable_MountingBlock_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.MountingBlock.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Strong and durable block, ideal for fortified constructions, especially due to its fire resistance..
        /// </summary>
        internal static string Solid_Immovable_RedBrick_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.RedBrick.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Red Brick.
        /// </summary>
        internal static string Solid_Immovable_RedBrick_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.RedBrick.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Natural and flammable foliage, common in forest areas. It can be used to decorate and enrich the natural scenery..
        /// </summary>
        internal static string Solid_Immovable_TreeLeaf_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.TreeLeaf.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tree Leaf.
        /// </summary>
        internal static string Solid_Immovable_TreeLeaf_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.TreeLeaf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An element that absorbs and destroys everything it touches..
        /// </summary>
        internal static string Solid_Immovable_Void_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Void.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Void.
        /// </summary>
        internal static string Solid_Immovable_Void_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Void.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An impenetrable, solid barrier. Resistant to natural forces and unaffected by other elements..
        /// </summary>
        internal static string Solid_Immovable_Wall_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Wall.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wall.
        /// </summary>
        internal static string Solid_Immovable_Wall_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Wall.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A wet sponge. Its density is slightly greater than a dry sponge, making it difficult to ignite in this state. If dry sponges are placed below, it will always reposition itself to the lowest point. It can be dried by heating..
        /// </summary>
        internal static string Solid_Immovable_WetSponge_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetSponge.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sponge (wet).
        /// </summary>
        internal static string Solid_Immovable_WetSponge_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.WetSponge.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A natural, flammable material often used in constructions. Burns easily when in contact with fire..
        /// </summary>
        internal static string Solid_Immovable_Wood_Description {
            get {
                return ResourceManager.GetString("Solid.Immovable.Wood.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wood.
        /// </summary>
        internal static string Solid_Immovable_Wood_Name {
            get {
                return ResourceManager.GetString("Solid.Immovable.Wood.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dark gray, slightly grainy powder that resembles the remains of wood or other burnt materials..
        /// </summary>
        internal static string Solid_Movable_Ash_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Ash.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ash.
        /// </summary>
        internal static string Solid_Movable_Ash_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Ash.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A not-so-powerful bomb that explodes upon colliding with neighboring elements..
        /// </summary>
        internal static string Solid_Movable_Bomb_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Bomb.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bomb.
        /// </summary>
        internal static string Solid_Movable_Bomb_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Bomb.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An unstable substance that spreads and infects corruptible materials, causing unstoppable destruction across the world..
        /// </summary>
        internal static string Solid_Movable_Corruption_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Corruption.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corruption (movable).
        /// </summary>
        internal static string Solid_Movable_Corruption_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Corruption.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dry soil, the foundation for vegetation. Turns into mud when exposed to water..
        /// </summary>
        internal static string Solid_Movable_Dirt_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Dirt.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dirt.
        /// </summary>
        internal static string Solid_Movable_Dirt_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Dirt.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An explosive that causes a massive explosion with a large destruction radius, affecting extensive areas and creating significant debris and secondary effects. It only explodes when exposed to high temperatures or comes into contact with hot elements like lava or fire..
        /// </summary>
        internal static string Solid_Movable_Dynamite_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Dynamite.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dynamite.
        /// </summary>
        internal static string Solid_Movable_Dynamite_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Dynamite.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dense and durable rock. Melts into lava under extreme heat and crumbles into sand after prolonged water exposure..
        /// </summary>
        internal static string Solid_Movable_Grass_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Grass.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grass.
        /// </summary>
        internal static string Solid_Movable_Grass_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Grass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Frozen water in solid form. Slippery and melts back into water when exposed to heat..
        /// </summary>
        internal static string Solid_Movable_Ice_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Ice.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ice.
        /// </summary>
        internal static string Solid_Movable_Ice_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Ice.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dense mixture of dirt and water. When heated, it dries up and turns back into dirt..
        /// </summary>
        internal static string Solid_Movable_Mud_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Mud.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mud.
        /// </summary>
        internal static string Solid_Movable_Mud_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Mud.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A white, crystalline powder formed by small, shiny grains. Dissolves when it comes into contact with water..
        /// </summary>
        internal static string Solid_Movable_Salt_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Salt.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salt.
        /// </summary>
        internal static string Solid_Movable_Salt_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Salt.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fine, loose grains that flow and accumulate easily. Under extreme heat, it fuses into glass..
        /// </summary>
        internal static string Solid_Movable_Sand_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Sand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sand.
        /// </summary>
        internal static string Solid_Movable_Sand_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Sand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accumulated ice crystals in light flakes. Melts into water when exposed to heat..
        /// </summary>
        internal static string Solid_Movable_Snow_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Snow.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Snow.
        /// </summary>
        internal static string Solid_Movable_Snow_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Snow.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A dense and durable rock. Melts into lava under extreme heat and crumbles into sand after prolonged water exposure..
        /// </summary>
        internal static string Solid_Movable_Stone_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.Stone.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stone.
        /// </summary>
        internal static string Solid_Movable_Stone_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.Stone.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Performs a moderate explosion with great destructive power, primarily affecting solids and leaving remnants of smoke and fire. It only explodes when exposed to high temperatures or comes into contact with hot elements like lava or fire..
        /// </summary>
        internal static string Solid_Movable_TNT_Description {
            get {
                return ResourceManager.GetString("Solid.Movable.TNT.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TNT.
        /// </summary>
        internal static string Solid_Movable_TNT_Name {
            get {
                return ResourceManager.GetString("Solid.Movable.TNT.Name", resourceCulture);
            }
        }
    }
}
